gluster/redant

redant_libs/volume_ops.py

Creating,Starting and Stopping volume functionalities have
been added.

Basic Volume operations

---

redant_libs/peer_ops.py
redant_libs/redant_resources.py

sys.path.append added to work in all the files

Added the path

---

redant_libs/volume_ops.py

Imported the logging module and tested the logs for volume ops.

Added logging in volume ops

---

redant_libs/volume_ops.py

Volume Info and Volume delete have been added

---

redant_libs/peer_ops.py

Added --xml in peer detach

---

tests/test_peer_probe.py

Started working on test case

---

redant_libs/support_libs/relog.py

Removed cls from static methods

Static methods don't have cls

---

redant_libs/gluster_libs/peer_ops.py
redant_libs/redant_resources.py

Modified the import paths in redant_resources and peer_ops so that it can start running

Modified peer_ops and redant_resources

---

redant_libs/gluster_libs/peer_ops.py

Added format specifiers in peer_ops.

Added format specifiers

---

redant_libs/redant_mixin.md

Image url was wrong. Modified the url. Image is visible now.

Image url corrected

---

redant_libs/gluster_libs/peer_ops.py

Added function annotation in peer_ops
Updates : #31 

Added function annotations in peer_ops

---

redant_libs/gluster_libs/volume_ops.py

Exceptions are raised based on the return value and logging
is done accordingly complying to the design doc.

Exceptions and Logging

---

redant_libs/support_libs/logging.md

Modified the logging.md file:
Added format
Added Levels
Updates: #42 

Added logging format in logging.md

---

.github/workflows/linting.yml

Added python linting to github workflow to check for typos and other code styling issues.
Updates: #47 

Added linter to workflow

---

runner_thread.py

Concerned file : runner_thread.py
Fixes: #51

Fixing flake and pylint

---

redant_libs/gluster_libs/volume_ops.py

Strings are formatted and annotations are updated
Updates: #50  , #31

Strings and annotations corrected

---

.vscode/settings.json
redant_libs/support_libs/io_ops.py

Added the annotations and changed the way of using format specifiers
Update: #45

Annotations and format specifiers

---

redant_libs/gluster_libs/peer_ops.py

Modified peer ops with autopep8 tool
Also changed the logs with proper format
Updates: #43 #58 #50 

Tested peer ops with flake8 and pylint

---

CONTRIBUTING.md

Added the commands to stylethe file using autopep8, pylint and flake8.
Updates: #60 

Modified contributing.md file

---

redant_libs/support_libs/relog.py

Fixing flake and lint issues in relog.py

---

redant_libs/support_libs/rexe.py

Removed the linting and flake issues.
Checked using flake8 and pylint
Updates: #58

Flaked and linted rexe file

---

redant_libs/gluster_libs/volume_ops.py
redant_libs/redant_mixin.py

flake8 and pylint errors are removed and default log level
is also removed while logging. VolumeOps module is added in
redant_mixin.py
Updates: #58

Fixing Pylint and flake8 errors

---

redant_libs/gluster_libs/volume_ops.py
redant_libs/support_libs/io_ops.py

The volume mount operation is shifted from io_ops to
VolumeOps library
Fixes: #73

Volume Mount operation is shifted to VolumeOps

---

requirements.txt

Added pylint, flake8 and autopep8 in requirements.txt
Updates: #78

Added pylint, flake8 and autopep8 in requirements

---

redant_libs/redant_mixin.py

Addition of io_ops library into redant_mixin.py
updates: #82 

Added io_ops to redant_mixin

---

redant_libs/gluster_libs/peer_ops.py
redant_libs/support_libs/io_ops.py

Fixed the docstring in io_ops and peer_ops library
Updates: #84

Fixed the docstring

---

CONTRIBUTING.md

Added the .pylintrc file in the command for pylint.
Updates: #60

Modified the contributing.md file

---

.github/workflows/linting.yml
.pylintrc
redant_libs/support_libs/rexe.py

Created a .pylintrc file using 
```js
pylint --generate-rcfile > .pylintrc
```
Now we can modify the same for the warnings that are not actually errors
The warnings that I removed by adding them in the .pylintrc :
```js
disable=E1101,
E0401,
R0801,
R0903,
C0103,
W0703,
R0902
```
Updates: #58

Created a pylintrc file

---

test_list_builder.py

Added test_list_builder.
Rn it creates a list of tests and returns the same
Updates: #85

Added test_list_builder

---

README.md

Adding design doc link to the readme for a better understanding for anyone looking to contribute and learn about Redant framework.
Desciption:
Fixes: #95

Adding design doc to readme file file

---

README.md

STEP-BY_STEP => STEP-BY-STEP
Updates: #97

Small change in readme

---

tests/glusterd_start_stop_test.py
tests/volume_create_delete_test.py

One test case performing volume operations and
one test case performing glusterd service operations
are added.
Updates: #93

Basic test cases are added

---

redant_libs/gluster_libs/gluster_ops.py
redant_libs/redant_mixin.py

Gluster Ops lib is added which has functionalities
for stating and stopping glusterd service.
Fixes: #91

Adding GlusterOps library

---

parsing/redant_params_handler.py
redant_test_main.py

Changes done in this commit,
1. Added cmd-line parsing options for
-> Test directory
-> Log directory
2. Enforced certain cmd-lin params as
required.
3. Resolved a dependency issue when invoking
the redant_test_main
Updates: #103

Enhancing redant_test_main

---

parent_test.py
tests/sample_test.py

Started working on parent_test
Created the basic functions and added the standard info.
Updates: #75

Added parent_test

---

runner_thread.py
tests/parent_test.py

Parent_test:
============
Modified init and configure
Runner_thread:
==============
Removed the mixin call using RE_MIXIN and modified TC_OBJ as per the changes in Parent_test
Updates: #75

Modified Parent_Test and runner_thread

---

parsing/redant_params_handler.py

The function return a dictionary with nodes info consisting
of hostname,ip,user and passwd.
Fixes: #118

Added function to return nodes info

---

runner_thread.py

Added the data types for client list, server list, log path and log level.
Updates: #31

Added the data types as per PEP-3107 standards

---

tests/functional/glusterd/test_glusterd_start_stop.py
tests/parent_test.py

the tc accesses server from parent test and
works successfully along with other components
Updates: #127

glusterd_start_stop tc working successfully

---

redant_libs/support_libs/io_ops.py

Changed the names of args of func.
Added path in ls command
Fixes: #111

Changes in io_ops

---

tests/functional/glusterd/test_glusterd_start_stop.py
tests/functional/glusterd/test_peer_probe_detach.py
tests/functional/glusterd/test_volume_create_delete.py

Peer probe and volume test cases are working
successfully integrating with all the components.
Updates: #127

Peer probe and volume test case working

---

support/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_volume_list_options.py

Extra functionalities are added in volume ops and
a test case is added to test them.
Fixes: #152 

Volume Ops and test case added

---

support/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_comparision.py

test case for comparision of performance is addded and
unmount volume funtion is added in volumeOps
Fixes: #156

Comparision test_case added and unmount volume in VolumeOps

---

config/config.yml
core/parsing/params_handler.py

Hostname is added in the servers_info in the config file
and is passed in the params handler accordingly.
Fixes: #150

Hostname is added to config

---

README.md
tools/clean_pycache

A Bash script has been added which handles the operation of
clearning out the Cache files.
Fixes: #174

Script for cleaning caache files in python

---

config/CONFIG_README.md
config/config.yml
core/parsing/params_handler.py
core/runner_thread.py
support/ops/support_ops/rexe.py
tests/parent_test.py

Config file is simplified and parsing is accordingly modified
Fixes: #150

Config File Enhancement

---

support/ops/gluster_ops/peer_ops.py
tests/functional/glusterd/test_peer_probe_detach.py

Function to create a cluster given a list of servers
is added in the peer ops library
Fixes: #159

Cluster creation funtionality added

---

support/rexe.py

Added the exec_command to get the required parameters to continue the execution of the commands after rebooting of nodes take place.
Fixes : #188

Added the code to handle the error in case of rebooting the node

---

support/rexe.py
tests/parent_test.py

Added Terminate function in Rexe to handle disconnection.
Updates: #179

[Lib] Adding terminate in Rexe.

---

support/ops/gluster_ops/peer_ops.py

Added the return types in function.
Removed the non-matching docstrings.
Fixes: #182
Updates: #172

Modified the peer ops file

---

core/test_runner.py
support/relog.py

1. Directories for different volume types as passed from the TCs.
2. Logfile names are appended with timestamp along with the name of volType.
Updates: #196 

Log dir structure is enhanced

---

core/parsing/params_handler.py
core/redant_main.py
core/runner_thread.py
core/test_runner.py
tests/parent_test.py

The config hashmap is passed from the params handler to the
parent test.
Fixes: #193

Passing the config hashmap to the parent test.

---

support/mixin.py
support/ops/gluster_ops/gluster_ops.py
support/ops/gluster_ops/peer_ops.py
support/ops/gluster_ops/volume_ops.py
support/ops/support_ops/io_ops.py
support/relog.py
support/rexe.py
tests/example/sample_component/test_sample.py
tests/functional/glusterd/test_peer_probe_detach.py
tests/functional/glusterd/test_volume_create_delete.py

1. Added return statements in ops
2. Added docstrings for the same
3. Modified the docstrings that did not match the operation.
4. Changed class names for ops from snake_case to CamelCase.
Fixes: #172

Standardized the code

---

config/CONFIG_README.md
support/ops/OPS_README.md

A readme for writing the ops library has been added and
config readme has been enhanced
Fixes: #195 

Ops Readme has been added

---

tests/README.md

Added the steps to write a test case from scratch
Fixes: #198

Added procedure to write a test case

---

support/ops/gluster_ops/peer_ops.py
support/relog.py
support/rexe.py
tests/functional/glusterd/test_peer_probe_detach.py
tests/functional/glusterd/test_volume_create_delete.py
tests/parent_test.py

Fixing cluster creation and cluster deletion fn

---

support/ops/abstract_ops.py
support/ops/gluster_ops/gluster_ops.py
support/ops/gluster_ops/peer_ops.py
support/ops/gluster_ops/volume_ops.py
support/ops/support_ops/io_ops.py
tests/example/sample_component/test_file_creation.py
tests/example/sample_component/test_sample.py

Abstract Ops is added and ops libraries are accodingly modified
to inherit the abstract ops.
Fixes: #153

Abstract Ops is added

---

tests/README.md

Modified the link to the ops readme.
Fixes : #217

Modified the link in the readme

---

core/redant_main.py
core/result_handler.py

As mentioned in the issue, the total time was not getting stored in the
result file. Hence added the same.
Fixes: #237

Added the total time information in the result file

---

core/redant_main.py
core/result_handler.py
requirements.txt

Added an option to store the results in excel sheet. Right now, it
displays the basic test stats but later we can also add memory and other
detailed stats as well.
Fixes: #234

Added option for storing results in excel sheet

---

core/parsing/params_handler.py
core/parsing/test_parser.py
core/redant_main.py

Check is added for existence and accessibility of config_file
Fixes: #231

Check is added for existence and accessibility of config_file

---

README.md

Added information about the flags.
Fixes: #245 

Added information about the flags

---

common/ops/support_ops/io_ops.py

Basic io functions like creating a file or a directory
and checking is path exists is added.
Fixes: #246

Basic io functions are added

---

common/ops/gluster_ops/volume_ops.py
tests/parent_test.py

This data structure will contain information
about the bricks as well as the mountpoints and
their corresponding server and clients.
Fixes: #255

Datastructure for volume level data.

---

common/ops/gluster_ops/volume_ops.py
config/config.yml
tests/example/sample_component/test_vol_creation.py

Dispersed and distributed-dispersed volume type creation is added and
according values of bricks are changed in config file for a 3 server
setup and some pylint fixes are are made. the new volume types are added
in the sample test case for volume creation.
Fixes: #265

Dispersed Volume and Distributed-Dispersed Volume creation is added

---

tests/example/sample_component/test_sample.py

Converting the TC as nonDisruptive.

---

README.md
docs/RPIndex.md

Desciption:
Fix links in the main readme and the RPIndex:
* Fixing broken links to the docs indexes 
* Turning absolute links to internal docs into relative links

docs: fix links

---

common/ops/gluster_ops/gluster_ops.py
common/ops/gluster_ops/volume_ops.py
common/ops/support_ops/io_ops.py

Added args in IO_Ops, Peer_Ops, Volume_Ops. Replaced the wrong args
specified with the correct ones.
Fixes: #284

Modified docstrings in all the ops

---

config/CONFIG_README.md
config/config.yml
core/parsing/params_handler.py
core/redant_main.py
core/test_list_builder.py
core/test_runner.py

when 'skip-test' comment is added in the test case then
that particular test case is skipped and is not executed
Fixes: #207

Flag for skipping the test is added

---

README.md
docs/BP/migratingTC.md
docs/BPIndex.md

Added the steps to be followed for migrating a test
case from `glusto-tests` to `redant`.
Fixes: #295
Fixes: #
(If it just updates the Issue)
Updates: #

[Doc] Test case migration doc.

---

tests/functional/glusterd/test_default_log_level_of_cli.py

Migrated the test case from glusto-test.
Made modifications as per the functionalities in redant.
Updates : #292
Fixes : #303

Added test_default_log_level_of_cli

---

common/ops/gluster_ops/gluster_ops.py

Removed the cmd and node labels to prevent the issue to occur.
Fixes: #321

Changed the execute_command call in is_glusterd_running

---

.github/workflows/linting.yml
common/ops/gluster_ops/peer_ops.py
core/environ.py
tools/linting.sh

when peer probed function is added to wait until peer connects
and function is added to check if peer is connected and few
other functions are modified.
Fixes: #235

PeerOps Modified

---

common/ops/gluster_ops/volume_ops.py

Fixes: #328 
Fixes: #
(If it just updates the Issue)
Updates: #

Fixing the typo which leads to test failure

---

common/ops/gluster_ops/gluster_ops.py

* Removed the condition to explicitly convert node to list
* Changed the condition to return True if ret is 1.
Fixes: #331

Fixed wait_for_glusterd issues

---

common/ops/gluster_ops/gluster_ops.py
tests/functional/glusterd/test_change_reserve_limit_to_wrong_values.py
tests/functional/glusterd/test_default_log_level_of_cli.py
tests/functional/glusterd/test_default_max_bricks_per_process.py
tests/functional/glusterd/test_enable_storage_reserve_volume.py
tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
tests/functional/glusterd/test_glusterd_quorum_command.py
tests/functional/glusterd/test_glusterd_set_reset_reserve_limit.py
tests/functional/glusterd/test_op_version.py

Description:
Migrated the [test-case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py)
Updates: #292 
Fixes: #316 

Added test_glusterd_friend_updates_on_node_rejoin

---

tests/functional/glusterd/test_updates_in_options_file_on_quorum_changes.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_updates_in_options_file_on_quorum_changes.py)
Made modifications as per the redant pattern and ops.
Updates: #292
Fixes: #363

Migrated test_updates_in_options_file_on_quorum_changes.py

---

common/mixin.py
common/ops/gluster_ops/profile_ops.py
tests/example/sample_component/test_profile_ops.py

Profile operations are added in the profile_ops library
and an example test case is also added and changes are made in
the mixin.py file to incorporate the profile_ops.
Fixes: #381

Profiles operation are added

---

README.md
docs/RP/Common/Index.md
docs/RP/Common/rexe.md
docs/RP/Core/Index.md

[Doc] Updating docs.

---

common/ops/gluster_ops/brick_ops.py
docs/BP/Ops/brick_ops.md
docs/BP/Ops/opsIndex.md

Added the documentation regarding brick ops for a better understanding.
Fixes: #393

[Doc] Added doc about brick ops

---

common/ops/gluster_ops/peer_ops.py
docs/BP/Ops/opsIndex.md
docs/BP/Ops/peer_ops.md

Added documentation regarding peer ops.
Fixes: #414

Added doc for peer ops

---

docs/BP/Ops/opsIndex.md
docs/BP/Ops/rexe.md

[Doc] Adding documentation for Rexe functions

---

core/environ.py

[Core] Logger invocation correction

---

core/result_handler.py
core/test_list_builder.py
core/test_runner.py

Added the summary stats in result_handler component.
Fixes: #417

Added the summary stats in results

---

docs/BP/Ops/volume_ops.md

Added documentation for BP volume ops
Fixes: #394

Added documentation for BP volume ops

---

core/environ.py
tests/d_parent_test.py
tests/nd_parent_test.py

[Test] Adding vol option cleanup in d_parent_test

---

common/ops/gluster_ops/peer_ops.py

if the state of peer status is 3 then the probe is success
Fixes: #430

Peer probe success checks for peer state as 3

---

tests/functional/glusterd/test_glusterd_selinux.py

ret_msg is updated with new value from the latest command execution.
Fixes: #468

ret_msg value is updated

---

common/ops/gluster_ops/brick_ops.py

Added get_all_bricks
Fixes: #473

Added the function get_all_bricks

---

common/ops/gluster_ops/brick_ops.py

Added get_online_bricks_list and get_offline_bricks_list.
Fixes: #475

Added the functions in brick ops

---

common/ops/support_ops/io_ops.py
tests/functional/glusterd/test_volume_status.py

Migrated the test case [test_volume_status](https://github.com/gluster/glusto-tests/blob/b9ecce005bd7a71942188802d151e96b281bab05/tests/functional/glusterd/test_volume_status.py)
Also, fixed the io_ops library.
Updates: #292
Fixes: #375

Migrated test_volume_status TC

---

common/mixin.py
common/ops/gluster_ops/peer_ops.py
common/ops/support_ops/machine_ops.py
common/rexe.py
docs/BP/Ops/README.md
docs/BP/Ops/machine_ops.md
docs/BP/Ops/rexe.md
tests/d_parent_test.py
tests/example/sample_component/test_machine_ops.py
tests/nd_parent_test.py

Added machine ops which takes care of machine
state. To support it, test has been added in example.
Also, enhanced the terminate of d_parent and nd_parent
tests.
Fixes: #478

[FRMV] Machine ops and related test

---

tests/example/sample_component/test_brick_ops.py

get_offline_bricks list
Added a test case to check the following ops
* get_online_bricks_list
* get offline bricks list

Added a test case to check the get_online_bricks_list and

---

MAINTAINERS

Modifying Maintainers list on actual contributions.

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/gluster_ops.py
docs/BP/Ops/brick_ops.md
tests/example/sample_component/test_brick_ops.py

Added the following functions
1. get_bricks_offline
2. get_bricks_online
3. wait_for_bricks_to_go_offline
4. wait_for_bricks_to_come_online
Fixes: #496

Brick ops enhancement

---

common/ops/support_ops/io_ops.py
docs/BP/Ops/README.md
docs/BP/Ops/io_ops.md
tests/example/sample_component/test_io.py

1. Get file stat
2. Get file permission
Fixes: #479

[Common] Adding functions to IO Ops

---

common/mixin.py
common/ops/gluster_ops/mount_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_brick_log_messages.py
tests/functional/glusterd/test_volume_status.py

Migrated TC [test_brick_log_messages](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_brick_log_messages.py)
Also, added mount_ops library.
Fixes: #503 
Updates: #292 

Migrated test_brick_log_messages and added mount_ops

---

tests/functional/glusterd/test_volume_set_when_glusterd_stopped_on_one_node.py

Migrated TC [test_volume_set_when_glusterd_stopped_on_one_node](https://github.com/gluster/glusto-tests/tree/master/tests/functional/glusterd)
Fixes: #508 
Updates: #292 

Migrated TC test_volume_set_when_glusterd_stopped_on_one_node

---

tests/functional/glusterd/test_rebalance_hang.py

[Test] Migrating test_rebalance_hang

---

tests/functional/glusterd/test_brick_status_when_quorum_not_met.py

Migration of -
`test_brick_status_when_quorum_not_met`
Fixes: #357

[Test] Migration of a brick test.

---

common/ops/gluster_ops/gluster_ops.py
tests/functional/glusterd/test_glusterd_default_volume_behavior_quorum_options.py

Fix return value and update docstring

---

common/ops/gluster_ops/peer_ops.py
common/ops/gluster_ops/rebalance_ops.py
tests/d_parent_test.py
tests/functional/glusterd/test_rebalance_when_quorum_not_met.py

1. Migration of TC
2. Fixing the peer issue
Fixes: #520

[Test] migration of a test case in rebalance

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/gluster_ops.py
common/ops/gluster_ops/mount_ops.py
common/ops/gluster_ops/volume_ops.py
core/environ.py
tests/functional/glusterd/test_glusterd_gluster_process_stop_start_cycle.py

Migrated TC [test_glusterd_gluster_process_stop_start_cycle](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_gluster_process_stop_start_cycle.py)
Fixes: #515 
Updates: #292 

Migrated test_glusterd_gluster_process_stop_start_cycle

---

common/ops/abstract_ops.py
tests/functional/glusterd/test_gluster_does_not_do_posix_lock_when_multiple_client.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_gluster_does_not_do_posix_lock_when_multiple_client.py)
Updates: #292
Fixes: #527

Migrated test_gluster_does_not_do_posix_lock_when_multiple_client

---

common/ops/gluster_ops/brick_ops.py
core/environ.py
docs/BP/Ops/brick_ops.md
tests/d_parent_test.py
tests/example/sample_component/test_brick_ops.py
tests/functional/glusterd/test_add_brick_when_quorum_not_met.py
tests/functional/glusterd/test_rebalance_new_node.py

[Common] Brick addition and listing

---

tests/functional/glusterd/test_change_reserve_limit.py
tests/nd_parent_test.py

Migration of [test_case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_change_reserve_limit.py)
Updates: #292
Fixes: #419
Signed-off-by: srijan-sivakumar ssivakmu@redhat.com

Migration of test_change_reserve_limit.py

---

config/config.yml

[Config] Tests added to config.yml

---

common/ops/gluster_ops/gluster_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_volume_get.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_volume_get.py)
Updates: #292
Fixes: #529

Migrated test_volume_get

---

common/ops/gluster_ops/volume_ops.py
tests/nd_parent_test.py

Terminate enhancement and volume status fix

---

common/ops/gluster_ops/gluster_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_volume_delete.py

Migrated TC [test_volume_delete](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_delete.py)
Fixes: #543 
Updates: #292 

Migrated test_volume_delete

---

config/config.yml
core/environ.py
core/redant_main.py
core/runner_thread.py
core/test_list_builder.py
core/test_runner.py
tests/functional/glusterd/test_add_brick_when_quorum_not_met.py
tests/functional/glusterd/test_remove_brick_when_quorum_not_met.py

Following changes have been done
1. Adding framework logging for checking test execution
2. Condition check before going into the code section for
nondisruptive tests.
3. Test fixes
Fixes: #550

[Core][Common][Test] Framework fix

---

tests/d_parent_test.py

Resetting the volume options seems to be a costly transaction. Hence making it optional.

[Test] Making reset optional

---

core/environ.py
tests/d_parent_test.py

Volume reset for cluster level options.

---

common/ops/gluster_ops/brick_ops.py

Update Add brick with force option

---

tests/d_parent_test.py

MIssing items in dict iterations

---

common/ops/gluster_ops/brick_ops.py
tests/functional/glusterd/test_restart_glusterd_while_rebalancing.py

Migration of [test_restart_glusterd_while_rebalancing.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_restart_glusterd_while_rebalancing.py) from glusto to redant
Updates: #292
Fixes: #584

Migration of test_restart_glusterd_while_rebalancing.py

---

tests/functional/glusterd/test_gluster_volume_status_xml_dump.py

* Made the test case generic
* Added dist-arb volume in the test case
Fixes: #592

Modified test_gluster_vol_status_xml_dump

---

common/ops/gluster_ops/brick_ops.py
tests/functional/glusterd/test_add_brick.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_add_brick.py)
Updates: #292
Fixes: #351

Migrated test_add_brick

---

common/ops/support_ops/machine_ops.py
core/environ.py
core/redant_main.py
core/test_runner.py
requirements.txt

Halo and hard terminate introduction

---

README.md

Modified the Main readme for displaying default cli output.

Adding Flags as cli output

---

common/ops/gluster_ops/volume_ops.py
config/config.yml
tests/functional/glusterd/test_volume_reduce_replica.py

Migration of test case [test](https://github.com/gluster/glusto-tests/blob/2fd283331817cbe7070c820525420698da4bddbb/tests/functional/glusterd/test_volume_reduce_replica.py)
Fixes: #542

[Test] Migrate test_volume_reduce_replica.py

---

tests/functional/glusterd/test_remove_brick_after_restart_glusterd.py

test_remove_brick_after_restart_glusterd
Fixes: #619

[Test] Migration of a glusto TC

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_volume_operations.py

Migrated TC [test_volume_operations](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_operations.py)
Fixes: #624 
Updates: #292 

Migrated TC test_volume_operations

---

common/ops/gluster_ops/volume_ops.py
tests/example/sample_component/test_vol_ops.py

Tested the get_subvol function and modified a sample
test for those who want to check it.
Fixes: #622, #481

[Common][TestM] Ops and Test migration

---

common/ops/support_ops/machine_ops.py
tests/d_parent_test.py

Added had terminate in all tests in d_parent_test
and also ip tables flush inside hard terminate.

[Core][Test] Cleanup fix

---

README.md

Added detailed design doc link and made some link changes.
Signed-off-by: srijan-sivakmuar ssivakum@redhat.com

Main readme updation

---

docs/BP/Ops/volume_ops.md

Certain functions were not documented.
Added the doc for the same.
Fixes: #640

Added documentation for volume ops

---

common/ops/gluster_ops/peer_ops.py
docs/BP/Ops/peer_ops.md

Added the documentation for the newly added functions in peer ops.
Fixes: #644

Added documentation for peer ops

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/peer_ops.py
common/ops/gluster_ops/shared_storage_ops.py
common/ops/gluster_ops/volume_ops.py
docs/BP/Ops/brick_ops.md
docs/BP/Ops/volume_ops.md
tests/functional/glusterd/test_peer_probe.py
tests/functional/glusterd/test_peer_status.py
tests/functional/glusterd/test_volume_create.py
tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py

Fix:
Fixed small list indices error and return value check  error in the TCs.

Fix few TCs and ops

---

docs/BP/Ops/rebalance_ops.md

Rebalance ops doc modified.
Added rebalance stop details.
Fixes: #654

Added documentation for rebalance ops

---

docs/BP/Ops/profile_ops.md

Added documentation for profile ops.
Fixes: #652

Added documentation for profile_ops

---

docs/BP/Ops/brick_ops.md

Added docs for newly added functions in brick ops
Fixes: #646

Added docs for brick ops

---

common/ops/support_ops/machine_ops.py
docs/BP/Ops/machine_ops.md

Added doc for the newly added ops in machine ops.
Fixes: #649

Added doc for machine ops

---

common/ops/support_ops/io_ops.py
common/ops/support_ops/machine_ops.py
tests/functional/glusterd/test_enabling_glusterd_debug_mode.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_enabling_glusterd_debug_mode.py)
Updates: #292
Fixes: #639

Migrated test_enabling_glusterd_debug_mode

---

common/ops/gluster_ops/volume_ops.py
tests/example/sample_component/test_vol_ops.py

Added the function and tested the same in the test_vol_ops test case.
Fixes: #669

Added bulk_volume_creation function

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/volume_ops.py

Removed the hardcoded force values in ops.
Fixes: #672

Remoeved hardcoded force values

---

common/ops/gluster_ops/volume_ops.py
tests/example/sample_component/test_vol_ops.py
tests/functional/glusterd/test_gluster_detect_drop_of_outbound_traffic.py
tests/functional/glusterd/test_volume_status_with_absent_bricks.py

Added log_volume_info_nad_status and is_volume_exported.
Fixes: #675

Added more volume ops

---

common/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_change_reserve_limit_to_wrong_values.py
tests/functional/glusterd/test_localtime_logging_and_opversion_negative_case.py
tests/functional/glusterd/test_lower_gluster_op_version.py
tests/functional/glusterd/test_op_version.py
tests/functional/glusterd/test_setting_volume_level_option_to_cluster.py
tests/functional/glusterd/test_volume_set_with_quorum_enabled.py

Added TC to check for localtime logging option and a few negative TCs as per this .t [cli_peer_and_volume_operations](https://github.com/gluster/glusterfs/blob/devel/tests/line-coverage/cli-peer-and-volume-operations.t).

[Test]Added new TC for localtime logging

---

common/ops/gluster_ops/brick_ops.py

Added two functions in brick ops:
* delete_bricks
* is_broken_symlinks_present_on_bricks
Fixes: #678

Added more functions in brick ops

---

tests/functional/arbiter/test_data_delete.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_data_delete.py)
Updates: #292
Fixes: #689

Migrated test_data_delete

---

common/mixin.py
common/ops/gluster_ops/auth_ops.py
tests/example/sample_component/test_vol_ops.py

Added auth ops

---

common/mixin.py
common/ops/gluster_ops/bitrot_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_volume_features_for_line_coverage.py

Test: Added a TC for line coverage

---

common/ops/gluster_ops/heal_ops.py
tests/example/sample_component/test_heal_ops.py

Added:
* monitor_heal_completion
* is_heal_complete
* get_heal_info
* is_volume_in_split_brain
* get_heal_info_split_brain
Added a sample test case to verify the same.
Fixes: #691

Added heal ops

---

common/ops/gluster_ops/gluster_ops.py
config/config.yml
tests/functional/glusterd/test_glusterd_memory_consumption_increase.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_glusterd_memory_consumption_increase.py).
Updates: #292
Fixes: #687

Migrated test_glusterd_memory_consumption_increase

---

common/ops/support_ops/io_ops.py
tests/functional/arbiter/test_no_data_loss_arbiter_vol_after_rename_file.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_no_data_loss_arbiter_vol_after_rename_file.py)
Fixes: #704
Updates: #292

Migrated test_no_data_loss_arbiter_vol_after_rename_file

---

common/ops/gluster_ops/brick_ops.py
tests/functional/glusterd/test_remove_brick_scenarios.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_remove_brick_scenarios.py)
Fixes: #667
Updates: #292

Migrated test_remove_brick_scenarios

---

common/ops/gluster_ops/heal_ops.py
tests/example/sample_component/test_heal_ops.py

Added:
1. is_shd_daemon_running
2. is_shd_daemonized
3. get_heal_info_summary
4. get_self_heal_daemon_pid
Fixes: #700

Added daemon related functions in heal ops

---

common/relog.py
common/rexe.py
core/environ.py
core/parsing/params_handler.py
core/parsing/test_parser.py
core/redant_main.py

- Perform ssh as current (possibly unprivileged) user
- Factor out ssh connection routine into dedicated function
- Omit loading private keys for ssh connection
- Tolerate missing 'excluded_tests' key in config file
- Sanitize conf file loading
- Sanitize handling of fatal conditions
- Symlink log dir of latest run to 'latest'
- Make message about invalid log level more helpful
Desciption:
Fixes: #
(If it just updates the Issue)
Updates: #

UI improvements / refinements

---

common/ops/support_ops/io_ops.py
tests/functional/arbiter/test_oom_on_client_heal_is_in_progress_arbiter.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_oom_on_client_heal_is_in_progress_arbiter.py)
Updates: #292
Fixes: #707

Migrated test_oom_on_client_heal_is_in_progress_arbiter

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_profile_simultaneously_on_different_nodes.py
tests/functional/glusterd/test_remove_brick_after_restart_glusterd.py
tests/functional/glusterd/test_shared_storage.py

Fix:
Updated the logic of the TC to account for race conditions and also
fixed the faulty logic for a few TCs, Ops

TestFix: Fixed the TC failures found in nightly run

---

common/ops/gluster_ops/heal_ops.py
tests/functional/arbiter/test_resolving_meta_data_split_brain_extended_attributes.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_resolving_meta_data_split_brain_extended_attributes.py)
Updates: #292
Fixes: #709

Migrated test_resolving_meta_data_split_brain_extended_attributes.py

---

tests/functional/arbiter/test_split_brain.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_split_brain.py)
Updates: #292
Fixes: #712

Migrated test_split_brain

---

README.md
docs/BP/Ops/peer_ops.md
docs/RP/Core/result_handler.md
tests/README.md

1. Added supported and tested distro information
2. Corrected the markdown annotations to right code
type.
Fixes: #701, #721

[Doc] Doc refactoring and supported os info

---

core/result_handler.py

The raw time format is converted to HH:MM:SS format and optional day
output if required.
Fixes: #718

[Core] Reformatting time format in output

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/volume_ops.py
core/environ.py
tests/example/sample_component/test_brick_ops.py
tests/example/sample_component/test_expand_shrink_volume.py
tests/functional/glusterd/test_add_brick.py
tests/functional/glusterd/test_create_vol_with_used_bricks.py
tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
tests/functional/glusterd/test_restart_glusterd_while_rebalancing.py

Added the expand_volume ops, and the other ops called inside it.
Fixes: #725

Ops: Added expand_volume op

---

common/ops/gluster_ops/volume_ops.py
tests/d_parent_test.py
tests/functional/arbiter/test_afr_read_write.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_afr_read_write.py)
Added verify_all__process_of_volume_are_online
Fixes: #723
Updates: #292

Migrated test_afr_read_write

---

common/ops/gluster_ops/heal_ops.py
tests/example/sample_component/test_heal_ops.py

Added the following heal ops:
* enable_self_heal_daemon
* disable_self_heal_daemon
* do_bricks_exist_in_shd_volfile
Fixes: #728

Added heal ops required for arbiter

---

.gitignore

Desciption: Adding vscode to gitignore.
Signed-off-by: srijan-sivakumar ssivakum@redhat.com

Gitignore adding vscode

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/volume_ops.py
core/environ.py
tests/example/sample_component/test_brick_ops.py

This addition will allow test cases modifying the
volume configuration on brick level to be made
non disruptive.
Fixes: #732

[Core] Sanitize enhancement for change in volume brick counts

---

common/mixin.py
common/ops/gluster_ops/snapshot_ops.py

Added snapshot ops like:
- enable_uss
- disable_uss
- is_uss_enabled
- is_uss_disabled
- is_snapd_running
Updates: #706

Ops: Added basic snapshot ops required for glusterd TCs

---

config/config.yml

Changing the distributed count for a distributed volume in config file from 4->3

Changing default config value for dist volume

---

common/ops/gluster_ops/bitrot_ops.py
common/ops/gluster_ops/snapshot_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_volume_reset.py

Migrated TC [test_volume_reset](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_reset.py)
Fixes: #746 
Updates: #292 

Migrated TC test_volume_reset

---

common/ops/gluster_ops/heal_ops.py
tests/functional/arbiter/brick_cases/test_impact_of_replace_brick_for_glustershd.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/brick_cases/test_impact_of_replace_brick_for_glustershd.py)
Updates: #292
Fixes: #735

Migrated test_impact_of_replace_brick_for_glustershd.py

---

tests/functional/arbiter/test_replacing_all_arbiter_bricks_in_the_volume.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_replacing_all_arbiter_bricks_in_the_volume.py)
Updates: #292
Fixes: #751

Migrated test_replacing_all_arbiter_bricks_in_the_volume.py

---

tests/functional/arbiter/brick_cases/test_cyclic_brick_kill_list.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/brick_cases/test_cyclic_brick_kill_list.py)
Updates: #292
Fixes: #734

Migrated test_cyclic_brick_kill_list

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/volume_ops.py
tests/example/sample_component/test_expand_shrink_volume.py

Description:
Added the shrink_volume and form_brick_list_to_remove_bricks op
Fixes: #736

Ops: Added shrink_volume op

---

README.md

Tested Redant in fedora 34 and runs smoothly.

Updated the supported and tested distro detail

---

common/ops/gluster_ops/peer_ops.py
common/ops/gluster_ops/volume_ops.py
common/ops/support_ops/machine_ops.py
tests/functional/glusterd/test_volume_reset.py

[Common] FQDN to IP conv in vol status

---

tests/functional/glusterd/test_enabling_glusterd_debug_mode.py

Desciption: Changing the path for the glusterd.service as we have CI with RPM installation now.
Fixes: #769

[TestFix] Changing glusterd.service path

---

tests/functional/dht/test_nuke_happy_path.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/dht/test_nuke_happy_path.py)
Updates: #292
Fixes: #760

Migrate test_nuke_happy_path

---

common/ops/gluster_ops/mount_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/glusterd/test_add_brick_when_quorum_not_met.py
tests/functional/glusterd/test_profile_start_with_quorum_not_met.py
tests/functional/glusterd/test_reserved_port_range_for_gluster.py
tests/functional/glusterd/test_validate_auth_allow_and_auth_reject.py
tests/functional/glusterd/test_volume_status_xml.py

Fix:
Updated the TCs to use the `excep` flag to check for negative scenarios
and raise an exception only if the outcome is not as expected
Fixes: #638

Updated the negative case handling in few of the TCs

---

common/ops/support_ops/io_ops.py

Added get_pathinfo
Fixes: #773

Added io ops

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/volume_ops.py
tests/example/sample_component/test_brick_ops.py

Added select_bricks_to_bring_offline and the ops related to the same
Fixes: #767

Added brick ops

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/snapshot_ops.py
common/ops/gluster_ops/volume_ops.py
common/ops/support_ops/machine_ops.py
core/environ.py
tests/d_parent_test.py
tests/example/sample_component/test_snap_ops.py
tests/functional/glusterd/test_change_reserve_limit.py
tests/functional/glusterd/test_concurrent_set.py
tests/functional/glusterd/test_create_vol_with_used_bricks.py
tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
tests/functional/glusterd/test_glusterd_quorum.py
tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
tests/functional/glusterd/test_peer_probe.py
tests/functional/glusterd/test_profile_operations.py
tests/functional/glusterd/test_profile_simultaneously_on_different_nodes.py
tests/functional/glusterd/test_quorum_syslog.py
tests/functional/glusterd/test_rebalance_hang.py
tests/functional/glusterd/test_rebalance_new_node.py
tests/functional/glusterd/test_volume_create.py
tests/functional/glusterd/test_volume_operations.py
tests/functional/glusterd/test_xml_dump_of_gluster_volume_status_during_rebalance.py
tests/vol_destroy_test.py

Desciption: Addition of snapshot ops.
Fixes: #706

[Core][Common] Snap ops addition

---

common/mixin.py
common/ops/gluster_ops/glusterfind_ops.py
common/ops/gluster_ops/peer_ops.py
common/ops/support_ops/io_ops.py
tests/example/sample_component/test_glusterfind_ops.py

Added the ops required for glusterfind TCs
Also, added the remove_file op.
Fixes: #776

Ops: Added glusterfind ops

---

common/ops/support_ops/io_ops.py

Converted the list to string in rmdir() in io_oops.py

Fix: Updated the function to use string instead of list

---

CONTRIBUTING.md

Changed the upstream link from `srijan-sivakumar` user to the gluster group.

Changing Upstream link

---

tests/functional/glusterfind/test_gfind_create_cli.py

Migrated the TC [test_gfind_create_cli](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_create_cli.py) from glusto.
Updates: #292

Test: Migrated TC test_gfind_create_cli

---

README.md
core/redant_main.py
core/result_handler.py
core/runner_thread.py
core/test_runner.py

[Core] Result Handler improvement.

---

tests/functional/afr/test_afr_cli_no_splitbrain_resolution.py

Migrated
[test_afr_cli_no_splitbrain_resolution.py](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_afr_cli_no_splitbrain_resolution.py)
Updates: #292

Migrated test_afr_cli_no_splitbrain_resolution.py

---

tests/functional/afr/test_afr_cli_gfid_splitbrain.py

Migrated
[test_afr_cli_gfid_splitbrain](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_afr_cli_gfid_splitbrain.py)
Updates: #292

Migrated test_afr_cli_gfid_splitbrain

---

tests/functional/glusterfind/test_gfind_post_cli.py

Migrated TC [test_gfind_post_cli](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_post_cli.py)
Updates: #292 

Migrated TC test_gfind_post_cli

---

core/environ.py
tests/functional/afr/test_file_permission_and_mode.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_file_permission_and_mode.py)
Updates: #292

Migrated test_file_permission_and_mode

---

tests/functional/glusterfind/test_gfind_pre_cli.py

Migrated TC [test_gfind_pre_cli](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_pre_cli.py)
Updates: #292 

Migrated TC test_gfind_pre_cli

---

tests/functional/glusterfind/test_gfind_post_cli.py
tests/functional/glusterfind/test_gfind_rename.py

Migrated TC [test_gfind_rename_cli](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_rename.py)
Updates: #292 

Migrated TC test_gfind_rename_cli

---

tests/functional/glusterfind/test_gfind_type_option.py

Migrated TC [test_gfind_type_option](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_type_option.py)
Updates: #292 

Migrated TC test_gfind_type_option

---

common/ops/support_ops/io_ops.py
tests/functional/glusterfind/test_gfind_modify_files.py

Migrated TC [test_gfind_modify_files](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_modify_files.py)
Also, added the `append_string_to_file` op.
Updates: #292 

Migrated TC test_gfind_modify_files

---

tests/functional/afr/test_gfid_assignment_on_dist_rep_vol.py

Migrated
[test_gfid_assignment_on_dist_rep_vol](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_gfid_assignment_on_dist_rep_vol.py)
Updates: #292

Migrated test_gfid_assignment_on_dist_rep_vol.

---

common/ops/support_ops/io_ops.py
tests/functional/glusterfind/test_gfind_delete_file.py

Migrated TC [test_gfind_delete_file](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_delete_file.py)
Updates: #292 

Migrated TC test_gfind_delete_file

---

tests/functional/afr/test_gfid_assignment_on_lookup.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_gfid_assignment_on_lookup.py)
Updates: #292

Migrated test_gfid_assignment_on_lookup

---

tests/functional/afr/test_heal_command_unsuccessful_as_bricks_down.py

Migrated [test
casee](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_heal_command_unsuccessful_as_bricks_down.py)
Updates: #292

Migrated test_heal_command_unsuccessful_as_bricks_down

---

common/ops/gluster_ops/snapshot_ops.py
tests/example/sample_component/test_snap_ops.py
tests/functional/snapshot/test_auto_delete.py

Test being migrated,
[test_auto_delete](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_auto_delete.py)
Updates: #292

Migrating snap auto delete test

---

README.md

Adding vscode badge. Just a small improvement in the main README.

Adding VSCode badge for repo

---

core/environ.py
core/runner_thread.py

Added the exception handling when object is being
instantiated. The object instantiation contains
the steps for connection establishment to remote
servers.
If the connection establishment fails, exception
is raised. This is now handled by the addition
of try-except block and hence the exception
thrown here won't cascade to process failure.
Fixes: #820

[Core] Exception handling for constructor invocation.

---

tests/functional/afr/test_heal_info_should_have_fixed_fields.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_heal_info_should_have_fixed_fields.py)
Updates: #292

Migrated test_heal_info_should_have_fixed_fields

---

tests/functional/authentication/test_auth_allow_with_rebalance.py

Migrated TC [test_auth_allow_with_rebalance](https://github.com/gluster/glusto-tests/blob/master/tests/functional/authentication/test_auth_allow_with_rebalance.py)
Updates: #292 

Migrated TC test_auth_allow_with_rebalance

---

tests/functional/afr/test_client_side_quorum_with_fixed_validate_max_bricks.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_client_side_quorum_with_fixed_validate_max_bricks.py)
Updates: #292

Migrated test_client_side_quorum_with_fixed_validate_max_bricks

---

common/rexe.py
core/environ.py
tests/functional/afr/test_readlink.py
tools/file_dir_ops.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_readlink.py)
Updates: #292

Migrated test_readlink

---

tests/functional/authentication/test_verify_auth_reject_precedence.py

Migrated TC [test_verify_auth_reject_precedence](https://github.com/gluster/glusto-tests/blob/master/tests/functional/authentication/test_verify_auth_reject_precedence.py)
Updates: #292 

Migrated TC test_verify_auth_reject_precedence

---

tests/functional/authentication/test_vol_auth.py

Migrated TC [test_vol_auth](https://github.com/gluster/glusto-tests/blob/master/tests/functional/authentication/test_vol_auth.py)
Updates: #292 

Migrated TC test_vol_auth

---

tests/functional/afr/test_creating_deleting_files_reflect_available_space.py

Migrated
[test_creating_deleting_files_reflect_available_space](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_creating_deleting_files_reflect_available_space.py)
Updates: #292

 Migrated test_creating_deleting_files_reflect_available_space

---

tests/functional/afr/heal/test_dir_time_stamp_restoration.py
tests/vol_destroy_test.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/heal/test_dir_time_stamp_restoration.py)
Updates: #292

Migrated test_dir_time_stamp_restoration

---

common/ops/gluster_ops/snapshot_ops.py
tests/functional/snapshot/test_snap_invalid_names.py

[Test](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_invalid_names.py)
Updates: #292

[TestMigration] Migration test_snap_invalid_names

---

tests/functional/afr/test_shd_should_not_crash_executed_heal_info.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_shd_should_not_crash_executed_heal_info.py)
Updates: #292

Migrated test_shd_should_not_crash_executed_heal_info

---

tests/functional/snapshot/test_snap_glusterd_down.py

[Test](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_glusterd_down.py)
Updates: #292

[TestMigration] Migration of test_snap_glusterd_down

---

tests/functional/afr/test_split_brain_with_hard_link_file.py

Migrated [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_split_brain_with_hard_link_file.py#L32)
Updates: #292

Migrated test_split_brain_with_hard_link

---

common/ops/gluster_ops/snapshot_ops.py
tests/functional/snapshot/test_snap_invalid_cases.py

[Test](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_invalid_cases.py)
Updates: #292

[TestMigration] Migrating test_snap_invlid_cases

---

common/ops/gluster_ops/snapshot_ops.py
tests/functional/snapshot/test_snap_delete_snap_of_volume.py

[Test](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_delete_snap_of_volume.py)
Updates: #292

[TestMigration] Migrating test_snap_delete_snap_of_volume

---

tests/functional/afr/heal/test_heal_info_while_accessing_file.py

Migrated [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/heal/test_heal_info_while_accessing_file.py)
Updates: #292

Migrated test_heal_info_while_accessing_file

---

tests/functional/afr/test_gfid_heal.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_gfid_heal.py)
Updates: #292

Migrated test_gfid_heal

---

tests/functional/afr/heal/test_existing_shd_should_take_care_of_self_healing.py

Migrated
[test_existing_shd_should_take_care_of_self_healing](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/heal/test_existing_shd_should_take_care_of_self_healing.py)
Updates: #292

Migrated test_existing_shd_should_take_care_of_self_healing

---

tests/functional/arbiter/brick_cases/test_replica3_to_arbiter.py

Migrate the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/brick_cases/test_replica3_to_arbiter.py)
Updates: #292
Fixes: #775

Migrate test_replica3_to_arbiter

---

tests/functional/arbiter/test_mount_point_while_deleting_files.py

Migrated TC [test_mount_point_while_deleting_files](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_mount_point_while_deleting_files.py)
Updates: #292 
Migrated TC test_mount_point_while_deleting_files

Migrated TC test_mount_point_while_deleting_files

---

tests/functional/afr/test_heal_fail_1x3.py

Migrated the [test case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_heal_fail_1x3.py)
Updates: #292

Migrated test_heal_fail_1x3

---

core/environ.py
docs/BP/Core/README.md
docs/BP/Core/environ.md
docs/BPIndex.md

[Doc] Adding environ method details.

---

common/ops/support_ops/io_ops.py
tests/functional/arbiter/test_data_self_heal_algorithm_full_default.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_data_self_heal_algorithm_full_default.py)
Updates: #292

Migrated test_data_self_heal_algorithm_full_default

---

tests/functional/arbiter/test_gfid_self_heal.py

case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_gfid_self_heal.py)
Updates: #292

Migrated test_gfid_self_heal

---

common/ops/support_ops/io_ops.py
tests/functional/arbiter/test_create_snapshot_and_verify_content.py

Migrate TC [test_create_snapshot_and_verify_content](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_create_snapshot_and_verify_content.py)
Updates: #292 

Migrate TC test_create_snapshot_and_verify_content

---

common/ops/gluster_ops/heal_ops.py
common/ops/support_ops/io_ops.py
tests/functional/arbiter/test_heal_full_after_deleting_the_files_from_bricks.py

Migrated TC [test_heal_full_after_deletinng_files_from_bricks](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_heal_full_after_deleting_the_files_from_bricks.py)
Updates: #292 

Migrated TC test_heal_full_after_deletinng_files_from_bricks

---

common/ops/gluster_ops/brick_ops.py
common/ops/support_ops/machine_ops.py
core/parsing/params_handler.py
tests/example/sample_component/test_machine_ops.py

Fix:
Updated the ops and the parser to support multiple bricks within a node
Fixes: #541 

Updated bricks_root to handle multiple bricks within a node

---

common/ops/gluster_ops/mount_ops.py
common/ops/gluster_ops/snapshot_ops.py
common/ops/gluster_ops/volume_ops.py
core/environ.py
tests/example/sample_component/test_snap_ops.py

Addition of snap mount and unmount. Also handling its cleanup.
Fixes: #861

[Core][Common] Adding snap mount

---

tests/functional/arbiter/test_data_self_heal_algorithm_diff_heal_command.py

Migrated TC [test_data_self_heal_algorithm_diff_heal_command](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_data_self_heal_algorithm_diff_heal_command.py)
Updates: #292 

Migrated TC test_data_self_heal_algorithm_diff_heal_command

---

tests/functional/arbiter/test_data_self_heal_algorithm_diff_default.py

Migrated TC [test_data_self_heal_algorithm_diff_default](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_data_self_heal_algorithm_diff_default.py)
Updates: #292 

Migrated TC test_data_self_heal_algorithm_diff_default

---

tests/functional/arbiter/test_gluster_clone_heal.py

Migrated TC [test_gluster_clone_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_gluster_clone_heal.py)
Updates: #292 

Migrated TC test_gluster_clone_heal

---

MAINTAINERS

[MaintainersList]Dev team change

---

common/ops/support_ops/io_ops.py
tests/functional/arbiter/test_entry_self_heal_heal_command.py

Migrated TC [test_entry_self_heal_command](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_entry_self_heal_heal_command.py)
Updates: #292 

Migrated TC test_entry_self_heal_command

---

tests/functional/arbiter/test_remove_faulty_subvol_and_add_new_subvol.py

Migrated TC [test_remove_faulty_subvol_and_add_new_subvol](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_remove_faulty_subvol_and_add_new_subvol.py)
Updates: #292 

Migrated TC test_remove_faulty_subvol_and_add_new_subvol

---

config/config.yml
tests/functional/arbiter/test_self_heal_50k_files.py

Migrated TC [test_self_heal_50k_files](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_self_heal_50k_files.py)
Updates: #292 

Migrated TC test_self_heal_50k_files

---

tests/functional/arbiter/test_self_heal_algorithm_full_daemon_off.py

Migrated TC [test_self_heal_algorithm_full_daemon_off](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_self_heal_algorithm_full_daemon_off.py)
Updates: #292 

Migrated TC test_self_heal_algorithm_full_daemon_off

---

tests/functional/arbiter/test_self_heal_daemon.py

Migrated TC [test_self_heal_daemon](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_self_heal_daemon.py)
Updates: #292 

Migrated TC test_self_heal_daemon

---

config/config.yml

Fixing typo in config

---

tests/functional/arbiter/test_self_heal_differing_in_file_type.py

Migrated TC [test_self_heal_differing_in_file_type](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_self_heal_differing_in_file_type.py)
Updates: #292 

Migrated TC test_self_heal_differing_in_file_type

---

core/environ.py
tools/arequal_install.sh

Added the script and also the logic to install the script if not present
in the machines.
Fixes: #883

Added arequal-checksum install script

---

tests/functional/arbiter/test_data_self_heal_daemon_off.py

Migrated
[test_data_self_heal_daemon_off](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_data_self_heal_daemon_off.py)
Updates: #292

Migrated test_data_self_heal_daemon_off

---

tests/functional/arbiter/test_metadata_self_heal.py

Migrated TC [test_metadata_self_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_metadata_self_heal.py)
Updates: #292 

Migrated TC test_metadata_self_heal

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/arbiter/brick_cases/test_brickcases.py

Migrated TC [test_brickcases](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/brick_cases/test_brickcases.py)
Updates: #292 

Migrated TC test_brickcases

---

tests/functional/afr/test_replica_eager_lock.py

Migrated
[test_replica_eager_lock](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_replica_eager_lock.py)
Updates: #292

Migrated test_replica_eager_lock

---

common/ops/support_ops/machine_ops.py

The patch fixes the logic in
1. Snap lv remove function
2. Convert hostname to IP
Fixes: #892

[Common] Logical fix in machine ops

---

.github/PULL_REQUEST_TEMPLATE.md
common/ops/support_ops/io_ops.py

Description:
Updated the `get_mounts_stat` op to use the `file_dir_ops` script to stat a directory recursively.

Updated the get_mounts_stat op

---

README.md
docs/BP/Tools/migratingTC.md

This patch updates links, fix typos, correct commands
Fixes: #903

minor changes

---

MAINTAINERS

Modified maintainers file

---

tests/functional/arbiter/test_handling_data_split_brain_of_files_heal_command.py

Migrated
[test_handling_data_split_brain_of_files_heal_command](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/arbiter/test_handling_data_split_brain_of_files_heal_command.py)
Updates: #292

Migrted test_handling_data_split_brain_of_files_heal_command

---

config/config.yml
tests/functional/arbiter/test_self_heal_50k_files_heal_command_by_add_brick.py

Migrated TC [test_self_heal_50k_files_heal_command_by_add_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_self_heal_50k_files_heal_command_by_add_brick.py)
Updates: #292 

Migrated TC test_self_heal_50k_files_heal_command_by_add_brick

---

tests/functional/arbiter/test_verify_metadata_and_data_heal.py

Migrated TC [test_verify_metadata_and_data_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_verify_metadata_and_data_heal.py)
Updates: #292 

Migrated TC test_verify_metadata_and_data_heal

---

common/ops/gluster_ops/brick_ops.py
tests/functional/afr/test_manual_heal_full_should_trigger_heal.py

Migrated TC [test_manual_heal_full_should_trigger_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_manual_heal_full_should_trigger_heal.py)
Updates: #292 

Migrated TC test_manual_heal_full_should_trigger_heal

---

tests/functional/afr/test_manual_heal_should_trigger_heal.py

Migrated TC [test_manual_heal_should_trigger_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_manual_heal_should_trigger_heal.py)
Updates: #292 

Migrated TC test_manual_heal_should_trigger_heal

---

README.md
docs/BPIndex.md
docs/README.md
docs/RP/HLD.md
docs/RPIndex.md
docs/known_issues.md

Description: Adding a doc with important known issues info. Also some doc restructuring.
Fixes: #909

[Doc] Adding Known issues

---

config/config.yml

Updated the `excluded_list` under the `config` file to remove a TC which is working now and added the reason for exclusion for another TC.

Updated excluded tests list

---

tests/functional/afr/test_gfid_split_brain_resolution.py

Migrated TC [test_gfid_split_brain_resolution](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_gfid_split_brain_resolution.py)
Updates: #292 

Migrated TC test_gfid_split_brain_resolution

---

tests/functional/afr/test_dist_to_repl_automatic_heal_should_be_triggered.py

Migrated TC [test_dist_to_repl_automatic_heal_should_be_triggered](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_dist_to_repl_automatic_heal_should_be_triggered.py)
Updates: #292 

Migrated TC test_dist_to_repl_automatic_heal_should_be_triggered

---

common/ops/support_ops/machine_ops.py
config/config.yml
core/result_handler.py
tests/functional/glusterd/test_detach_node_used_to_mount.py
tests/functional/glusterd/test_quorum_syslog.py

1. Fixed the total runs count for a scenario when
all cases are skipped.
2. TEST_RES fix in a test.
3. Added check for distro in a case.
Fixes: #911

[Core][Common][Test] Exclude list fix

---

common/ops/support_ops/machine_ops.py

Clearing out the old *.socket files and other dirs
from /var/run/gluster dir.
Fixes: #874

[Common] Clearing out files and dirs

---

tests/functional/afr/test_conservative_merge_of_files_heal_command.py

Migrated TC [test_conservative_merge_of_files_heal_command](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_conservative_merge_of_files_heal_command.py)
Updates: #292 

Migrated TC test_conservative_merge_of_files_heal_command

---

tests/functional/afr/test_self_heal_with_diff_algorithm.py
tests/functional/arbiter/test_verify_metadata_and_data_heal.py

Migrated TC [test_self_heal_with_diff_algorithm](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_self_heal_with_diff_algorithm.py)
Updates: #292 

Migrated TC test_self_heal_with_diff_algorithm

---

tests/functional/afr/test_self_heal_with_full_algorithm.py

Migrated TC [test_self_heal_with_full_algorithm](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_self_heal_with_full_algorithm.py)
Updates: #292 

Migrated TC test_self_heal_with_full_algorithm

---

core/environ.py
core/redant_main.py
core/result_handler.py

Increased the amount of debug logs in redant_main
and also put some basic logging inside the result
handler.
Fixes: #932

[Core] Increased debug log penetration.

---

core/redant_main.py

[Core] Fixing logger obj call

---

docs/BP/TestNature.md
docs/BPIndex.md

Description: The added markdown helps people to understand what points are to be kept in mind for a test case to be marked as disruptive/non-disruptive.
Fixes: #924

[Doc] Deciding test nature markdown added

---

requirements.txt
tools/README.md
tools/log_server/README.md
tools/log_server/log_access.ini
tools/log_server/log_access.py
tools/log_server/log_access.sh

This patch aims to provide a way to quickly
access log dirs from remote server using a flask
server.
Fixes: #906

[Tool] Log access flask server

---

common/ops/gluster_ops/heal_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/afr/test_glustershd_on_all_volume_types.py
tests/functional/glusterd/test_volume_reduce_replica.py

Migrated TC [test_glustershd_on_all_volume_types](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_glustershd_on_all_volume_types.py)
Updates: #292 

Migrated TC test_glustershd_on_all_volume_types

---

common/ops/support_ops/io_ops.py
tests/functional/afr/test_default_granular_entry_heal.py

Migrated TC [test_default_granular_entry_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_default_granular_entry_heal.py)
And, added the op `occurences_of_pattern_in_file`.
Updates: #292 

Migrated TC test_default_granular_entry_heal

---

core/redant_main.py
docs/BP/CatchAllException.md
docs/BPIndex.md
tests/d_parent_test.py
tests/nd_parent_test.py

This patch covers two things,
1. Improved handling of exceptions in redant.
2. Converting the Exception class object  to str
in parent tests so that they can be pushed to xls.
Fixes: #936

[Core] Exception handling improvement

---

CONTRIBUTING.md
tools/README.md
tools/linting.sh

The linting check needs to be similar to GH actions,
plus a little simple.
Updates: #900

[Tool] Linting behavior similar to GH Actions

---

common/mixin.py
common/ops/support_ops/machine_ops.py
core/environ.py
core/runner_thread.py
tests/d_parent_test.py
tests/functional/authentication/test_auth_allow.py
tests/functional/authentication/test_auth_allow_reject_same_client.py
tests/functional/authentication/test_auth_reject_allow.py
tests/functional/authentication/test_fusereject.py
tests/functional/authentication/test_verify_auth_reject_precedence.py
tests/functional/glusterd/test_create_vol_with_used_bricks.py
tests/functional/glusterd/test_detach_node_used_to_mount.py
tests/functional/glusterd/test_gluster_does_not_do_posix_lock_when_multiple_client.py
tests/functional/glusterd/test_glusterd_quorum.py
tests/functional/glusterd/test_glusterd_split_brain.py
tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
tests/functional/glusterd/test_peer_probe_while_snapd_running.py
tests/functional/glusterd/test_quorum_syslog.py
tests/functional/glusterd/test_volume_create.py
tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py
tests/functional/glusterd/test_volume_status_show_bricks_online_though_brickpath_deleted.py
tests/lazy_parent_test.py
tests/nd_parent_test.py

Added a generic function to check for servers, clients, and bricks requirements for a TC.
Fixes: #937 

Added generic skip test function

---

core/test_runner.py

Updated the `testResult` value to check for value at first index, as the value passed for `TEST_RES` is a list.

Fixed test result handler

---

tests/functional/afr/test_heal_split_brain_command.py

Migrated TC [test_heal_split_brain_command](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_heal_split_brain_command.py)
Updates: #292 

Migrated TC test_heal_split_brain_command

---

config/config.yml

[Config] Adding a skip test

---

common/ops/support_ops/io_ops.py
common/rexe.py
tests/example/sample_component/test_io.py

Added timeout functionality for async command.
Fixes: #878 

Added timeout for async command

---

tests/functional/snapshot/test_validate_snap_del_gd_down.py

[Test](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_validate_snap_del_gd_down.py)
Updates: #292

[TestMigration] Migration of test_validate_snap_del_gd_down

---

config/config.yml
tests/functional/afr/test_brick_process_not_started_on_read_only_node_disks.py

Migrated TC [test_brick_process_not_started_on_read_only_node_disks](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_brick_process_not_started_on_read_only_node_disks.py)
Updates: #292 

Migrated TC test_brick_process_not_started_on_read_only_node_disks

---

tests/functional/afr/heal/test_data_split_brain_resolution.py

[Migrated TC tests/functional/afr/heal/test_data_split_brain_resolution.py](https://github.com/gluster/glusto-tests/blob/35f1b97a8ecee852b2543e87ceb2ebbe9cf4f6ca/tests/functional/afr/heal/test_data_split_brain_resolution.py)
Updates: #292
Signed-off-by: Sheetal Pamecha spamecha@redhat.com

Migrated TC tests/functional/afr/heal/test_data_split_brain_resolution.py

---

tests/functional/afr/heal/test_heal_info_no_hang.py

[Migrated TC tests/functional/afr/heal/test_heal_info_no_hang.py](https://github.com/gluster/glusto-tests/blob/35f1b97a8ecee852b2543e87ceb2ebbe9cf4f6ca/tests/functional/afr/heal/test_heal_info_no_hang.py)
Updates: #292
Signed-off-by: Sheetal Pamecha spamecha@redhat.com

Migrated TC tests/functional/afr/heal/test_heal_info_no_hang.py

---

tests/functional/snapshot/test_activate_on_create.py

Migrating [test_activate_on_create](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_activate_on_create.py)
Updates: #292

[Test] Migrating test_activate_on_create

---

tests/functional/snapshot/test_snap_clone_from_snap.py

Migrating [test_snap_clone_from_snap](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_clone_from_snap.py)
Updates: #292 

[Test] Migrating test_snap_clone_from_snap.py

---

tests/functional/snapshot/test_snap_info.py

Migrating [test_snap_info.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_info.py)
Updates: #292 

[Test] Migrating test_snap_info.py

---

config/config.yml
tests/functional/snapshot/test_snapshot_create.py

Migrating test case [test_snapshot_create](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snapshot_create.py)
Updates: #292 

[Test] Migration test_snapshot_create.py

---

common/ops/gluster_ops/brick_ops.py
tests/functional/afr/test_afr_reset_brick_heal_full.py

Migrated TC [test_afr_reset_brick_heal_full](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_afr_reset_brick_heal_full.py)
Updates: #292 

Migrated TC test_afr_reset_brick_heal_full

---

tests/functional/afr/test_multiple_clients_dd_on_same_file_default.py

Migrated TC [test_multiple_clients_dd_on_same_file_default](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_multiple_clients_dd_on_same_file_default.py)
Updates: #292

Migrated TC test_multiple_clients_dd_on_same_file_default

---

tests/functional/snapshot/test_snap_list_after_restart.py

Migrating [test_snap_list_after_restart.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_list_after_restart.py)
Updates: #292

[Test] Migrating test_snap_list_after_restart.py

---

tests/functional/snapshot/test_snap_uss_while_io.py

Migrating [test_snap_uss_while_io.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_uss_while_io.py)
Updates: #292 

[Test] Migrating test_snap_uss_while_io.py

---

tests/functional/afr/test_replace_brick_self_heal_io_in_progress.py

Migrated TC [test_replace_brick_self_heal_io_in_progress](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_replace_brick_self_heal_io_in_progress.py)
Updates: #292 

Migrated TC test_replace_brick_self_heal_io_in_progress

---

common/ops/support_ops/io_ops.py
tests/functional/afr/test_client_side_quorum_with_auto_option_overwrite_fixed.py

Migrated TC [test_client_side_quorum_with_auto_option_overwrite_fixed](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_client_side_quorum_with_auto_option_overwrite_fixed.py)
Updates: #292 

Migrated TC test_client_side_quorum_with_auto_option_overwrite_fixed

---

common/ops/support_ops/io_ops.py
tests/functional/afr/heal/test_metadata_split_brain_resolution.py

[Migrated TC tests/functional/afr/heal/test_metadata_split_brain_resolution.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/heal/test_metadata_split_brain_resolution.py)
Updates: #292

Migrated TC tests/functional/afr/heal/test_metadata_split_brain_resolution.py

---

tests/functional/afr/heal/test_no_glustershd_with_distribute.py

[Migrated TC tests/functional/afr/heal/test_no_glustershd_with_distribute.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/heal/test_no_glustershd_with_distribute.py)
Updates: #292

Migrated TC tests/functional/afr/heal/test_no_glustershd_with_distribute.py

---

tests/functional/afr/heal/test_impact_of_replace_brick_on_glustershd.py

[Migrated TC test_impact_of_replace_brick_on_glustershd.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/heal/test_impact_of_replace_brick_on_glustershd.py)
Updates: #292 

Migrated TC test_impact_of_replace_brick_on_glustershd.py

---

tests/functional/afr/test_client_side_quorum_with_auto_option.py

Migrated TC [test_client_side_quorum_with_auto_option](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_client_side_quorum_with_auto_option.py)
Updates: #292

Migrated TC test_client_side_quorum_with_auto_option

---

tests/functional/afr/heal/test_server_side_healing_happens_only_when_glustershd_running.py

Migrated TC [test_server_side_healing_happens_only_when_glustershd_running.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/heal/test_server_side_healing_happens_only_when_glustershd_running.py)
Updates: #292

Migrated TC test_server_side_healing_happens_only_when_glustershd_running.py

---

tests/functional/afr/test_client_side_quorum_with_multiple_volumes.py

Migrated TC [test_client_side_quorum_with_multiple_volumes](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_client_side_quorum_with_multiple_volumes.py)
Updates: #292 

Migrated TC test_client_side_quorum_with_multiple_volumes

---

common/ops/gluster_ops/snapshot_ops.py
tests/functional/afr/test_afr_with_snapshot.py
tests/functional/afr/test_afr_with_snapshot_delete.py
tests/functional/afr/test_afr_with_snapshot_rename.py

Migrated TC [test_afr_with_snapshot](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_afr_with_snapshot.py)
Divided the sub-TCs into multiple TCs
Updates: #292 

Migrated TC test_afr_with_snapshot

---

common/mixin.py
common/ops/gluster_ops/dht_ops.py
common/ops/gluster_ops/volume_ops.py
tests/functional/afr/test_add_brick_followed_by_remove_brick.py

Migrated TC [test_add_brick_followed_by_remove_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_add_brick_followed_by_remove_brick.py)
Also, added ops `is_layout_complete` and other dependent ops.
Updates: #292 

Migrated TC test_add_brick_followed_by_remove_brick

---

tests/functional/afr/test_self_heal_with_expand_volume.py

Migrated TC [test_self_heal_with_expand_volume](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_self_heal_with_expand_volume.py)
Updates: #292 

Migrated TC test_self_heal_with_expand_volume

---

tests/functional/afr/test_client_side_quorum_with_fixed_for_cross3.py

Migrated TC [test_client_side_quorum_with_fixed_for_cross3](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_client_side_quorum_with_fixed_for_cross3.py)
Updates: #292 

Migrated TC test_client_side_quorum_with_fixed_for_cross3

---

tests/functional/afr/test_split_brain_with_node_reboot.py

Migrated TC [test_split_brain_with_node_reboot](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_split_brain_with_node_reboot.py)
Updates: #292 

Migrated TC test_split_brain_with_node_reboot

---

tests/functional/afr/heal/test_self_heal_with_meta_data_entry_and_files_removed.py

[Migrated TC test_self_heal_with_meta_data_entry_and_files_removed.py](https://github.com/gluster/glusto-tests/blob/35f1b97a8ecee852b2543e87ceb2ebbe9cf4f6ca/tests/functional/afr/heal/test_self_heal_with_meta_data_entry_and_files_removed.py)
Updates:#292

Migrated TC test_self_heal_with_meta_data_entry_and_files_removed.py

---

tests/functional/afr/test_volume_set_options.py

Migrated TC [test_volume_set_options](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_volume_set_options.py)
Updates: #292 

Migrated TC test_volume_set_options

---

tests/functional/afr/test_metadata_self_heal_client_side_heal.py

Migrated TC [test_metadata_self_heal_client_side_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_metadata_self_heal_client_side_heal.py)
Updates: #292 

Migrated TC test_metadata_self_heal_client_side_heal

---

common/ops/gluster_ops/brick_ops.py
core/environ.py
tests/functional/glusterd/test_verify_df_output.py

Migrated TC [test_verify_df_output](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_verify_df_output.py)
Also, updated the `form_brick_cmd` function to take the unused bricks in case of multiple bricks per node
Updates: #292 

Migrated TC test_verify_df_output

---

config/config.yml
tests/functional/afr/test_arb_to_repl_conversion_with_io.py

Migrated TC [test_arb_to_repl_conversion_with_io](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_arb_to_repl_conversion_with_io.py)
Updates: #292 

Migrated TC test_arb_to_repl_conversion_with_io

---

tests/functional/afr/heal/test_self_heal_with_link_files.py

[Migrated TC test_self_heal_with_link_files.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/heal/test_self_heal_with_link_files.py)
Updates: #292

Migrated TC test_self_heal_with_link_files.py

---

common/ops/support_ops/machine_ops.py
config/config.yml
tests/functional/afr/test_write_io_mount_point_resumed_quorum_restored.py

Migrated TC [test_write_io_mount_point_resumed_quorum_restored](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_write_io_mount_point_resumed_quorum_restored.py)
Updates: #292 

Migrated TC test_write_io_mount_point_resumed_quorum_restored

---

tests/functional/snapshot/test_clone_snap.py

Migrated TC [test_clone_snap](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_clone_snap.py)
Updates: #292

Migrated TC test_clone_snap

---

config/config.yml
tests/functional/snapshot/test_256_snapshots.py

Migrated TC [test_256_snapshots](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_256_snapshots.py)
Updates: #292 

Migrated TC test_256_snapshots

---

tests/functional/afr/test_dir_gfid_heal_on_all_subvols.py
tests/functional/afr/test_write_io_mount_point_resumed_quorum_restored.py

Updated the script path for 2 TCs, as per the latest update.

Update script path for TCs

---

tests/functional/dht/test_rebalance_multiple_expansions.py

[Migrate TC tests/functional/dht/test_rebalance_multiple_expansions.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_multiple_expansions.py)
Updates: #292

Migrate TC tests/functional/dht/test_rebalance_multiple_expansions.py

---

common/ops/gluster_ops/mount_ops.py
common/ops/gluster_ops/snapshot_ops.py
common/ops/support_ops/io_ops.py
tests/example/sample_component/test_snap_ops.py
tests/functional/snapshot/test_snap_uss.py
tests/functional/snapshot/test_snap_uss_while_io.py
tests/functional/snapshot/test_uss_brick_down.py

Migrated TC [test_snap_uss](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_uss.py)
Updates: #292 

Migrated TC test_snap_uss

---

config/config.yml
tests/functional/snapshot/test_snap_delete_multiple.py

Migrated TC [test_snap_delete_multiple](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_delete_multiple.py)
Updates: #292 

Migrated TC test_snap_delete_multiple

---

common/ops/gluster_ops/snapshot_ops.py
tests/functional/snapshot/test_snap_rebalance.py

Migrated TC [test_snap_rebalance](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_rebalance.py)
Updates: #292 

Migrated TC test_snap_rebalance

---

tests/functional/snapshot/test_snap_self_heal.py

Migrated TC [test_snap_self_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_self_heal.py)
Updates: #292 

Migrated TC test_snap_self_heal

---

common/ops/gluster_ops/volume_ops.py
tests/functional/snapshot/test_snapshot_restore.py

Migrated TC [test_snapshot_restore](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snapshot_restore.py)
Updates: #292 

Migrated TC test_snapshot_restore

---

common/ops/gluster_ops/snapshot_ops.py
tests/functional/snapshot/test_uss_snap_restore.py

Migrated TC [test_uss_snap_restore](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_uss_snap_restore.py)
Updates: #292 

Migrated TC test_uss_snap_restore

---

common/ops/gluster_ops/snapshot_ops.py
tests/functional/snapshot/test_validate_snaps_dir_over_uss.py

Migrated TC [test_validate_snaps_dir_over_uss](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_validate_snaps_dir_over_uss.py)
Updates: #292 

Migrated TC test_validate_snaps_dir_over_uss

---

config/config.yml
tests/functional/snapshot/test_validate_snapshot_max_limit.py

Migrated TC [test_validate_snapshot_max_limit](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_validate_snapshot_max_limit.py)
Updates: #292 

Migrated TC test_validate_snapshot_max_limit

---

tests/functional/snapshot/test_mount_snap.py

Migrated TC [test_mount_snap](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_mount_snap.py)
Updates: #292 

Migrated TC test_mount_snap

---

tests/functional/snapshot/test_validate_snapshot_rebalance.py

Migrated TC [test_validate_snapshot_rebalance](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_validate_snapshot_rebalance.py)
Updates: #292

Migrated TC test_validate_snapshot_rebalance

---

common/ops/gluster_ops/snapshot_ops.py
tests/functional/snapshot/test_snap_uss_snapd.py

Migrated the TC [test_snap_uss_snapd](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_uss_snapd.py)
Updates: #292 

Migrated the TC test_snap_uss_snapd

---

common/ops/gluster_ops/snap_scheduler_ops.py
tests/functional/snapshot/test_snap_delete_existing_scheduler.py
tests/functional/snapshot/test_snap_scheduler_status.py

Mirgated the TC [test_snap_delete_existing_scheduler](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_delete_existing_scheduler.py)
Updates: #292 

Mirgated the TC test_snap_delete_existing_scheduler

---

tests/functional/disperse/test_ec_all_healtypes.py

[Migrated TC tests/functional/disperse/test_ec_all_healtypes.py](Migrated TC tests/functional/disperse/test_ec_all_healtypes.py)
Updates: #292

Migrated TC tests/functional/disperse/test_ec_all_healtypes.py

---

tests/functional/fuse_subdir/test_subdir_mount.py

Migrated TC [test_subdir_mount](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_subdir_mount.py)
Updates: #292 

Migrated TC test_subdir_mount

---

tests/functional/fuse_subdir/test_volume_set_ops_sub_dirs_mounted.py

Migrated TC [test_volume_set_ops_sub_dirs_mounted](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_volume_set_ops_sub_dirs_mounted.py)
Updates: #292 

Migrated TC test_volume_set_ops_sub_dirs_mounted

---

tests/functional/fuse_subdir/test_node_reboot_subdir_mounted.py
tests/functional/fuse_subdir/test_volume_set_ops_sub_dirs_mounted.py

Migrated TC [test_node_reboot_subdir_mounted](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_node_reboot_subdir_mounted.py)
Updates: #292 

Migrated TC test_node_reboot_subdir_mounted

---

tests/functional/fuse_subdir/test_multisubdir_with_multiclient.py

Migrated TC [test_multisubdir_with_multiclient](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_multisubdir_with_multiclient.py)
Updates: #292 

Migrated TC test_multisubdir_with_multiclient

---

tests/functional/fuse_subdir/test_leveldownsubdir_with_multiclient.py

Migrated TC [test_leveldownsubdir_with_multiclient](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_leveldownsubdir_with_multiclient.py)
Updates: #292 

Migrated TC test_leveldownsubdir_with_multiclient

---

tests/functional/fuse_subdir/test_fusesubdir_with_replacebrick.py

Migrated TC [test_fusesubdir_with_replacebrick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_fusesubdir_with_replacebrick.py)
Updates: #292 

Migrated TC test_fusesubdir_with_replacebrick

---

tests/functional/fuse_subdir/test_fusesubdir_with_addbrick.py

Migrated TC [test_fusesubdir_with_addbrick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_fusesubdir_with_addbrick.py)
Updates: #292

Migrated TC test_fusesubdir_with_addbrick

---

tests/functional/fuse_subdir/test_fusesubdir_with_removebrick.py

Migrated TC [test_fusesubdir_with_removebrick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_fusesubdir_with_removebrick.py)
Updates: #292 

Migrated TC test_fusesubdir_with_removebrick

---

tests/functional/fuse_subdir/test_auth_reject.py

Migrated TC [test_auth_reject](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_auth_reject.py)
Updates: #292 

Migrated TC test_auth_reject

---

tests/functional/fuse_subdir/test_fusesubdir_rename.py

Migrated TC [test_fusesubdir_rename](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_fusesubdir_rename.py)
Updates: #292 

Migrated TC test_fusesubdir_rename

---

common/ops/gluster_ops/mount_ops.py
tests/functional/fuse_subdir/test_auth_allow_fqdn.py

[Migrate Test tests/functional/fuse_subdir/test_auth_allow_fqdn.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_auth_allow_fqdn.py)
Updates: #292 

Migrate Test tests/functional/fuse_subdir/test_auth_allow_fqdn.py

---

tests/functional/fuse_subdir/test_auth_allow_ip_fqdn.py

[Migrated Tc tests/functional/fuse_subdir/test_auth_allow_ip_fqdn.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/fuse_subdir/test_auth_allow_ip_fqdn.py)
Updates: #292

Migrated Tc tests/functional/fuse_subdir/test_auth_allow_ip_fqdn.py

---

tests/functional/disperse/test_ec_add_brick.py

[Migrate TC tests/functional/disperse/test_ec_add_brick.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_add_brick.py)
Updates: #292

Migrate TC tests/functional/disperse/test_ec_add_brick.py

---

tests/functional/disperse/test_ec_verify_full_heal.py

Migrated TC [test_ec_verify_full_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_verify_full_heal.py)
Updates: #292 

Migrated TC test_ec_verify_full_heal

---

MAINTAINERS

Updating mail id

---

common/ops/gluster_ops/volume_ops.py
tests/functional/disperse/test_no_fresh_lookup_on_directory.py
tests/functional/fuse_subdir/test_subdir_mount.py

Migrated TC [test_no_fresh_lookup_on_directory](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_no_fresh_lookup_on_directory.py)
Updates: #292 

Migrated TC test_no_fresh_lookup_on_directory

---

common/ops/gluster_ops/brick_ops.py
common/ops/gluster_ops/heal_ops.py
common/ops/support_ops/io_ops.py
tests/functional/disperse/test_ec_open_fd.py

Migrated TC [test_ec_open_fd](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_open_fd.py)
Updates: #292

Migrated TC test_ec_open_fd

---

common/ops/gluster_ops/heal_ops.py
core/environ.py
docs/Common/Ops/peer_ops.md
tests/functional/disperse/test_ec_verify_datacorruption_during_full_heal.py

Migrated TC [test_ec_verify_datacorruption_during_full_heal](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_verify_datacorruption_during_full_heal.py)
Updates: #292

Migrated TC test_ec_verify_datacorruption_during_full_heal

---

common/ops/gluster_ops/volume_ops.py
tests/functional/disperse/test_ec_validate_volume_creation.py

Migrated Tc [test_ec_validate_volume_creation](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_validate_volume_creation.py)
Updates: #292 

Migrated Tc test_ec_validate_volume_creation

---

tests/functional/disperse/test_ec_heal_on_file_appends.py

Migrated TC [test_ec_heal_on_file_appends](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_heal_on_file_appends.py)
Updates: #292

Migrated TC test_ec_heal_on_file_appends

---

tests/functional/disperse/test_ec_replace_brick_after_add_brick.py

Migrated TC [test_ec_replace_brick_after_add_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_replace_brick_after_add_brick.py)
Updates: #292 

Migrated TC test_ec_replace_brick_after_add_brick

---

config/config.yml
tests/functional/disperse/test_ec_uss_snapshot.py
tests/functional/snapshot/test_snap_uss.py

Migrated TC [test_ec_uss_snapshot](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_uss_snapshot.py)
Updates: #292

Migrated TC test_ec_uss_snapshot

---

tests/functional/disperse/test_ec_data_delete.py

[Migrated TC test_ec_data_delete.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_data_delete.py)
Updates: #292

Migrated TC test_ec_data_delete.py

---

tests/functional/disperse/test_ec_data_intergrity.py

[Migrated TC test_ec_data_intergrity.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_data_intergrity.py)
Updates: #292

Migrated TC test_ec_data_intergrity.py

---

tests/functional/disperse/test_ec_remove_brick.py

Migrated TC [test_ec_remove_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_remove_brick.py)
Updates: #292 

Migrated TC test_ec_remove_brick

---

tests/functional/disperse/test_ec_quorumcount_6.py

Migrated TC [test_ec_quorumcount_6](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_quorumcount_6.py)
Updates: #292 

Migrated TC test_ec_quorumcount_6

---

tests/functional/disperse/test_ec_quorumcount_5.py

Migrated TC [test_ec_quorumcount_5](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_quorumcount_5.py)
Updates: #292 

Migrated TC test_ec_quorumcount_5

---

common/ops/gluster_ops/brick_ops.py
tests/functional/disperse/test_ec_remove_brick_operations.py

Migrated TC [test_remove_brick_operations](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_remove_brick_operations.py)
Updates: #292

Migrated TC ec_test_remove_brick_operations

---

common/ops/gluster_ops/auth_ops.py
common/ops/gluster_ops/mount_ops.py
common/ops/gluster_ops/volume_ops.py
config/config.yml
docs/Common/Ops/mount_ops.md
docs/Common/Ops/volume_ops.md
tests/functional/afr/test_afr_with_snapshot.py
tests/functional/afr/test_heal_fail_1x3.py
tests/functional/afr/test_metadata_self_heal_client_side_heal.py
tests/functional/authentication/test_auth_allow.py
tests/functional/authentication/test_auth_allow_with_rebalance.py
tests/functional/authentication/test_auth_reject_allow.py
tests/functional/authentication/test_verify_auth_reject_precedence.py
tests/functional/fuse_subdir/test_subdir_mount.py
tests/functional/glusterd/test_brick_port_after_stop_glusterd_modify_volume.py
tests/functional/glusterd/test_brickmux_brick_process.py
tests/functional/glusterd/test_change_reserve_limit.py
tests/functional/glusterd/test_detach_node_used_to_mount.py
tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
tests/functional/glusterd/test_glusterd_quorum.py
tests/functional/glusterd/test_glusterd_split_brain.py
tests/functional/glusterd/test_reserved_port_range_for_gluster.py
tests/functional/glusterd/test_validate_auth_allow_and_auth_reject.py
tests/functional/snapshot/test_snap_delete_existing_scheduler.py
tests/functional/snapshot/test_snap_scheduler_status.py
tests/functional/snapshot/test_validate_snap_scheduler.py

Fixed TCs and OPs that were failing in CI as per the latest run.

Fixed TCs failing in CI

---

tests/functional/disperse/test_ec_fops.py

Migrate TC[ tests/functional/disperse/test_ec_fops.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_fops.py)
Updates: #292
Signed-off-by: Sheetal Pamecha spamecha@redhat.com

Migrate TC tests/functional/disperse/test_ec_fops.py

---

tests/functional/disperse/test_ec_fops_brickdown.py

[Migrate TC tests/functional/disperse/test_ec_fops_brickdown.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_fops_brickdown.py)
Updates: #292

Migrate TC tests/functional/disperse/test_ec_fops_brickdown.py

---

tests/functional/disperse/test_ec_lookup_and_move_operations.py

Migrated TC [test_ec_lookup_and_move_operations](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_lookup_and_move_operations.py)
Updates: #292 

Migrated TC test_ec_lookup_and_move_operations

---

common/ops/gluster_ops/brick_ops.py
tests/functional/disperse/test_ec_reset.py

Migrated TC [test_ec_reset](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_reset.py)
Updates: #292 

Migrated TC test_ec_reset

---

common/ops/gluster_ops/dht_ops.py
tests/functional/dht/test_access_file.py

Migrated TC [test_access_file](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_access_file.py)
Also, added the function `find_new_hashed`
Updates: #292

Migrated TC test_access_file

---

common/ops/support_ops/io_ops.py
tests/functional/dht/test_delete_dir_with_self_pointing_linkto_files.py

Migrated TC [test_delete_dir_with_self_pointing_linkto_files](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_delete_dir_with_self_pointing_linkto_files.py)
Updates: #292

Migrated TC test_delete_dir_with_self_pointing_linkto_files

---

common/ops/support_ops/io_ops.py
tests/functional/dht/test_copy_huge_file_with_remove_brick_in_progress.py
tests/functional/disperse/test_ec_all_healtypes.py

Migrated TC [test_copy_huge_file_with_remove_brick_in_progress](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_copy_huge_file_with_remove_brick_in_progress.py)
Updates: #292

Migrated TC test_copy_huge_file_with_remove_brick_in_progress

---

common/ops/support_ops/io_ops.py
tests/functional/authentication/test_auth_allow_with_rebalance.py
tests/functional/dht/test_brick_full_add_brick_rebalance.py

Migrated TC [test_brick_full_add_brick_rebalance](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_brick_full_add_brick_rebalance.py)
Also, added the function `get_usable_size_per_disk`
Updates: #292

Migrated TC test_brick_full_add_brick_rebalance

---

config/config.yml
tests/functional/dht/test_accessing_file_when_dht_layout_is_stale.py

Migrated TC [test_accessing_file_when_dht_layout_is_stale](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_accessing_file_when_dht_layout_is_stale.py)
Updates: #292

Migrated TC test_accessing_file_when_dht_layout_is_stale

---

tests/functional/dht/test_add_brick_remove_brick_with_lookups_and_kernal_untar.py

Migrated TC [test_add_brick_remove_brick_with_lookups_and_kernel_untar](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_add_brick_remove_brick_with_lookups_and_kernal_untar.py)
Updates: #292 

Migrated TC test_add_brick_remove_brick_with_lookups_and_kernel_untar

---

tests/functional/dht/test_add_brick_rebalance_revised.py

Migrated TC [test_add_brick_rebalance_revised](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_add_brick_rebalance_revised.py)
Updates: #292

Migrated TC test_add_brick_rebalance_revised

---

config/config.yml
tests/functional/dht/test_add_brick_rebalance_with_self_heal_in_progress.py

Migrated TC [test_add_brick_rebalance_with_self_heal_in_progress](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_add_brick_rebalance_with_self_heal_in_progress.py)
Updates: #292

Migrated TC test_add_brick_rebalance_with_self_heal_in_progress

---

tests/functional/dht/test_add_brick_replace_brick_fix_layout.py

Migrated TC [test_add_brick_replace_brick_fix_layout](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_add_brick_replace_brick_fix_layout.py)
Updates: #292

Migrated TC test_add_brick_replace_brick_fix_layout

---

tests/functional/dht/test_brick_full_add_brick_remove_brick.py

Migrated TC [test_brick_full_add_brick_remove_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_brick_full_add_brick_remove_brick.py)
Updates: #292 

Migrated TC test_brick_full_add_brick_remove_brick

---

tests/functional/dht/test_delete_file_picked_for_migration.py

Migrated TC [test_delete_file_picked_for_migration](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_delete_file_picked_for_migration.py)
Updates: #292 

Migrated TC test_delete_file_picked_for_migration

---

tests/functional/dht/test_stop_glusterd_while_rebalance_in_progress.py

Migrate TC [test_stop_glusterd_while_rebalance_in_progress.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_stop_glusterd_while_rebalance_in_progress.py)
Updates: #292

 Migrate TC test_stop_glusterd_while_rebalance_in_progress.py

---

common/ops/gluster_ops/glusterd_ops.py

Issue:
The function `restart_glusterd` and `start_glusterd` was calling themselves in case the `start/restart` fo glusterd failed.
And, if there comes out to be some issue from the glusterd starting itself, then the process goes on for infinite times, resulting in a crash.
Fix:
Added a separate function `start_failed_glusterd` which handles the above scenario and executes the appropriate command.

Common: Fix infinite recursion in case of reset-failed glusterd

---

common/ops/support_ops/io_ops.py
tests/functional/dht/test_custom_xattr_healing_for_dir.py

Migrated TC [test_custom_xattr_healing_for_dir](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_custom_xattr_healing_for_dir.py)
Updates: #292 

Migrated TC test_custom_xattr_healing_for_dir

---

tests/functional/disperse/test_ec_eagerlock.py

Migrate TC [tests/functional/disperse/test_ec_eagerlock.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_eagerlock.py)
Updates: #292

Migrate TC tests/functional/disperse/test_ec_eagerlock.py

---

tests/functional/dht/test_time_taken_for_ls.py

Migrate TC [tests/functional/dht/test_time_taken_for_ls.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_time_taken_for_ls.py)
Updates: #292

Migrate TC tests/functional/dht/test_time_taken_for_ls.py

---

config/config.yml
tests/functional/dht/test_wipe_out_directory_permissions.py

Migrate TC [test_wipe_out_directory_permissions.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_wipe_out_directory_permissions.py)
Updates: #292 

Migrate TC test_wipe_out_directory_permissions.py

---

tests/functional/dht/test_stack_overflow.py

Migrate TC[ tests/functional/dht/test_stack_overflow.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_stack_overflow.py)
Updates: #292

Migrate TC tests/functional/dht/test_stack_overflow.py

---

common/ops/gluster_ops/dht_ops.py
tests/functional/dht/test_dht_copy_dir.py

Migrated TC [test_dht_copy_dir](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_dht_copy_dir.py)
Updates: #292

Migrated TC test_dht_copy_dir

---

tests/functional/dht/test_dht_create_dir.py

Migrated TC [test_dht_create_dir](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_dht_create_dir.py)
Updates: #292

Migrated TC test_dht_create_dir

---

tests/functional/dht/test_dht_custom_xattr.py

Migrated TC [test_dht_custom_xattr](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_dht_custom_xattr.py)
Updates: #292 

Migrated TC test_dht_custom_xattr

---

tests/functional/dht/test_sparse_file_creation_and_deletion.py

Migrate TC [test_sparse_file_creation_and_deletion.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_sparse_file_creation_and_deletion.py)
Updates: #292

Migrate TC test_sparse_file_creation_and_deletion.py

---

tests/functional/dht/test_dht_hash_value.py

Migrated TC [test_dht_hash_value](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_dht_hash_value.py)
Updates: #292 

Migrated TC test_dht_hash_value

---

tests/functional/dht/test_dir_change_perm.py

Migrated TC [test_dir_change_perm](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_dir_change_perm.py)
Updates: #292 

Migrated TC test_dir_change_perm

---

tests/functional/dht/test_restart_glusterd_after_rebalance.py

Migrate TC [test_restart_glusterd_after_rebalance.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_restart_glusterd_after_rebalance.py)
Updates: #292

Migrate TC test_restart_glusterd_after_rebalance.py

---

tests/functional/dht/test_dir_change_perm_recursive.py

Migrated TC [test_dir_change_perm_recusively](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_dir_change_perm_recursive.py)
Updates: #292

Migrated TC test_dir_change_perm_recusively

---

tests/functional/dht/test_directory_healing.py

Migrated TC [test_directory_healing](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_directory_healing.py)
Updates: #292 

Migrated TC test_directory_healing

---

tests/functional/dht/test_induce_holes_in_layout_by_removebrick_commit_then_fixlayout.py

Migrated TC [test_induc_holes_in_layout_by_removebrick_commit_then_fix_layout](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_induce_holes_in_layout_by_removebrick_commit_then_fixlayout.py)
Updates: #292

Migrated TC test_induc_holes_in_layout_by_removebrick_commit_then_fix_layout

---

tests/functional/dht/test_induce_holes_in_layout_by_removebrick_force_then_lookup.py

Migrated TC [test_induc_holes_in_layout_by_removebrick_force_then_lookup](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_induce_holes_in_layout_by_removebrick_force_then_lookup.py)
Updates: #292

Migrated TC test_induc_holes_in_layout_by_removebrick_force_then_lookup

---

tests/functional/dht/test_kill_brick_with_remove_brick.py

Migrated TC [test_kill_brick_with_remove_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_kill_brick_with_remove_brick.py)
Updates: #292

Migrated TC test_kill_brick_with_remove_brick

---

tests/functional/dht/test_rebalance_with_brick_down.py

Migrate TC[ tests/functional/dht/test_rebalance_with_brick_down.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_with_brick_down.py)
Updates: #292

Migrate TC tests/functional/dht/test_rebalance_with_brick_down.py

---

tests/functional/dht/test_rebalance_with_special_files.py

Migrate TC [tests/functional/dht/test_rebalance_with_special_files.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_with_special_files.py)
Updates: #292

Migrate TC tests/functional/dht/test_rebalance_with_special_files.py

---

tests/functional/dht/test_negative_exercise_add_brick_command.py

Migrated TC [test_negative_exercise_add_brick_command](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_negative_exercise_add_brick_command.py)
Updates: #292 

Migrated TC test_negative_exercise_add_brick_command

---

common/ops/gluster_ops/volume_ops.py
tests/functional/dht/test_rebalance_add_brick_command.py

Migrated TC [test_rebalance_add_brick_command](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_add_brick_command.py)
Updates: #292 

Migrated TC test_rebalance_add_brick_command

---

common/ops/support_ops/io_ops.py
tests/functional/dht/test_one_brick_full_add_brick_rebalance.py

Migrated TC [test_one_brick_full_add_brick_rebalance](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_one_brick_full_add_brick_rebalance.py)
Updates: #292 

Migrated TC test_one_brick_full_add_brick_rebalance

---

tests/functional/dht/test_rebalance_stop_mid_migration.py

Migrated TC [tests/functional/dht/test_rebalance_stop_mid_migration.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_stop_mid_migration.py)
Updates: gluster#292

Migrated TC tests/functional/dht/test_rebalance_stop_mid_migration.py

---

common/ops/support_ops/io_ops.py
tests/functional/dht/test_open_file_migration.py

Migrated TC [test_open_file_migration](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_open_file_migration.py)
Updates: #292 

Migrated TC test_open_file_migration

---

tests/functional/dht/test_rebalance_dir_file_from_multiple_clients.py

Migrated TC [test_rebalance_dir_file_from_multiple_clients](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_dir_file_from_multiple_clients.py)
Updates: #292 

Migrated TC test_rebalance_dir_file_from_multiple_clients

---

core/result_handler.py

Updated the results table/excel sheet to show the `Tests Passed` and `Tests Failed` count as well.

[Core] Added pass/fail count of TCs in results

---

config/config.yml
tests/functional/dht/test_rebalance_rename.py

Migrated TC [test_rebalance_rename](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_rename.py)
Updates: #292 

Migrated TC test_rebalance_rename

---

tests/functional/dht/test_rebalance_start_when_glusterd_down.py

Migrated TC [test_rebalance_start_when_glusterd_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_start_when_glusterd_down.py)
Updates: #292 

Migrated TC test_rebalance_start_when_glusterd_down

---

tests/functional/dht/test_volume_start_stop_while_rebalance_in_progress.py

Migrate TC [test_volume_start_stop_while_rebalance_in_progress.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_volume_start_stop_while_rebalance_in_progress.py)
Updates: #292

Migrate TC test_volume_start_stop_while_rebalance_in_progress.py

---

tests/functional/dht/test_rebalance_with_hidden_files.py

Migrated TC [test_rebalance_with_hidden_files.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_two_volumes.py)
Updates: #292

Migrated TC test_rebalance_with_hidden_files.py

---

common/ops/support_ops/io_ops.py
tests/functional/dht/test_rebalance_two_volumes.py

Migrate TC[ test_rebalance_two_volumes.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_two_volumes.py)
Updates: #292

Migrate TC test_rebalance_two_volumes.py

---

common/ops/gluster_ops/dht_ops.py
tests/functional/dht/test_lookup_dir.py

Migrated TC [test_lookup_dir](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_lookup_dir.py)
Updates: #292 

Migrated TC test_lookup_dir

---

common/ops/gluster_ops/rebalance_ops.py
tests/functional/dht/test_readdirp_with_rebalance.py

Migrated TC [test_readdirp_with_rebalance](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_readdirp_with_rebalance.py)
Updates: #292

Migrated TC test_readdirp_with_rebalance

---

tests/functional/dht/test_verify_create_hash.py

Migrated TC [test_verify_create_hash](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_verify_create_hash.py)
Updates: #292 

Migrated TC test_verify_create_hash

---

tests/functional/dht/test_rename_directory.py

Migrated TC [test_rename_directory](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rename_directory.py)
Updates: #292 

Migrated TC test_rename_directory

---

tests/functional/dht/test_pipe_character_and_block_device_files.py

Migrated TC [test_pipe_character_and_block_device_files](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_pipe_character_and_block_device_files.py)
Updates: #292

Migrated TC test_pipe_character_and_block_device_files

---

tests/functional/dht/test_exericse_rebalance_command.py

Migrate TC [test_exericse_rebalance_command.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_exericse_rebalance_command.py)
Updates: #292 

Migrate TC test_exericse_rebalance_command.py

---

tests/functional/dht/test_remove_brick_command_opitons.py

Migrate TC [test_remove_brick_command_opitons.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_remove_brick_command_opitons.py)
Updates: #292

Migrate TC test_remove_brick_command_opitons.py

---

tests/functional/dht/test_remove_brick_while_rebalance_is_running.py

Migrated TC[ test_remove_brick_while_rebalance_is_running.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_remove_brick_while_rebalance_is_running.py)
Updates: #292

Migrated TC test_remove_brick_while_rebalance_is_running.py

---

common/ops/support_ops/machine_ops.py
config/config.yml
tests/functional/arbiter/test_afr_read_write.py
tests/functional/arbiter/test_self_heal_50k_files.py
tests/functional/arbiter/test_self_heal_50k_files_heal_command_by_add_brick.py
tests/functional/dht/test_add_brick_rebalance_with_self_heal_in_progress.py
tests/functional/dht/test_wipe_out_directory_permissions.py
tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py
tests/functional/glusterd/test_setting_volume_option_with_more_than_4096_characters.py
tests/functional/glusterd/test_volume_set_when_glusterd_stopped_on_one_node.py
tests/functional/snapshot/test_snapshot_create.py
tests/functional/snapshot/test_validate_snap_del_gd_down.py

Added a check for RHGS installation in TCs, which doesn't work on upstream code.
So, that it doesn't get excluded in CI runs.
Also, updated the TCs which were failing due to "command execution hanging", to have a timeout.

Added check for RHGS installation

---

common/ops/support_ops/io_ops.py
tests/functional/dht/test_rebalance_files_with_holes.py

Migrated TC [test_rebalance_files_with_holes](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_files_with_holes.py)
Updates: #292

Migrated TC test_rebalance_files_with_holes

---

tests/functional/dht/test_remove_brick_no_commit_followed_by_rebalance.py

Migrated TC [test_remove_brick_no_commit_followed_by_rebalance.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_remove_brick_no_commit_followed_by_rebalance.py)
Updates: #292

Migrated TC test_remove_brick_no_commit_followed_by_rebalance.py

---

tests/functional/afr/heal/test_impact_of_replace_brick_on_glustershd.py
tests/functional/afr/heal/test_self_heal.py
tests/functional/afr/heal/test_self_heal_daemon_process.py
tests/functional/afr/heal/test_server_side_healing_happens_only_when_glustershd_running.py
tests/functional/afr/test_afr_cli_gfid_splitbrain.py

Fixed some issues in the AFR TCs like invalid comparisons and increased heal timeout.

Fixed few AFR TCs

---

tests/functional/multiplex/test_enabling_brick_mux.py

The logic of the TC was not correct for RHGS installation.
Updated the TC accordingly.

Fix multiplex tc

---

config/CONFIG_README.md
core/redant_main.py
core/result_handler.py
core/test_list_builder.py
core/test_runner.py

Updated the code to build the test list depending upon the volume types in the config file.
Fixes: #898 

Update to allow test runs based on config volume types

---

tests/flaky/arbiter/brick_cases/test_rmvrf_files.py
tests/flaky/dht/test_add_brick_rebalance_with_rsync_in_progress.py
tests/flaky/dht/test_copy_dir_subvol_down.py
tests/flaky/dht/test_copy_file_subvol_down.py
tests/flaky/dht/test_copy_huge_file_with_remove_brick_in_progress.py
tests/flaky/dht/test_verify_create_hash.py
tests/flaky/fuse_subdir/test_fusesubdir_with_replacebrick.py
tests/functional/afr/heal/test_server_side_healing_happens_only_when_glustershd_running.py
tests/functional/disperse/test_ec_all_healtypes.py
tests/functional/disperse/test_ec_data_delete.py
tests/functional/disperse/test_ec_data_intergrity.py
tests/functional/disperse/test_ec_fops.py
tests/functional/disperse/test_ec_fops_brickdown.py
tests/functional/disperse/test_ec_verify_datacorruption_during_full_heal.py
tests/functional/glusterd/test_verify_df_output.py
tests/functional/glusterfind/test_gfind_type_option.py
tests/functional/resource_leak/test_basic_memory_leaks.py
tests/functional/resource_leak/test_memory_leak_in_shd_with_cache_invalidation_on.py
tests/functional/resource_leak/test_memory_leaks_with_files_delete.py
tests/functional/resource_leak/test_verify_gluster_memleak_with_management_encryption.py
tests/functional/resource_leak/test_verify_gluster_memleak_with_ssl.py

This PR fixes some incorrect commands, typos in the TCs and marked some
more TCs as flaky (as per the current CI).

Fix: Marking tests as flaky, typos, incorrect commands

---

common/ops/gluster_ops/brick_ops.py
config/config.yml
docs/code_considerations.md
tests/functional/afr/heal/test_server_side_healing_happens_only_when_glustershd_running.py
tests/functional/dht/test_rebalance_add_brick_and_lookup.py

Added some doc for brick forming logic, fixed typo in a TC added an AFR TC in the excluded list
and added an RHGS installation check for a DHT TC.
Updates: #896

Doc updates and typo in TC

---

common/ops/support_ops/machine_ops.py
config/config.yml
tests/functional/arbiter/test_create_snapshot_and_verify_content.py
tests/functional/dht/test_add_brick_rebalance_with_self_heal_in_progress.py
tests/functional/dht/test_rebalance_add_brick_and_lookup.py
tests/functional/dht/test_wipe_out_directory_permissions.py
tests/functional/glusterd/test_default_ping_timer_and_epoll_thread_count.py
tests/functional/glusterd/test_glusterd_friend_updates_on_node_rejoin.py
tests/functional/glusterd/test_localtime_logging_and_opversion_negative_case.py
tests/functional/glusterd/test_rebalance_start_not_failed_with_socket_path_too_long.py
tests/functional/glusterd/test_setting_volume_option_with_more_than_4096_characters.py
tests/functional/snapshot/test_snapshot_create.py
tests/functional/snapshot/test_validate_snap_del_gd_down.py

The PR segregates tests that could run either on upstream/RHGS installation for glusterd, glusterfind components.

Skip tests working only on upstream/RHGS accordingly
