gluster/redant

redant_libs/support_libs/logging.md, redant_libs/support_libs/relog.py, redant_libs/support_libs/rexe.py, thread_runner.py
Changes:
1. Added a new method `rlog` to handle the generic way
of calls to logging. It takes two arguments of type string,
log_message and log_level wherein the default log_level is Info.
2. Modified the thread_runner and rexe with the logging changes.
3. Added logging.md to put out the design considerations.
=> Make logging API a little generic

redant_libs/support_libs/rexe.py
A return code way doesn't work with Paramiko and
hence added generic exception.
Fixes: #80
=> Modified exception to handle all exceptions.

tests/glusterd_start_stop_test.py, tests/sample_test.py, tests/test_sample_tc.py, tests/volume_create_delete_test.py
The remote_exec class variable has been changed to
redant which refers to the mixin object passed as reference
to the test case and forms a point of contact to the redant
framework from the test case.
Fixes: #106
=> remote_exec class variable changed to redant

tests/peer_probe_detach_test.py
remote_exec class variable name is now changed to redant
Fixes: #106 
=> remote_exec variable name is changed to redant

README.md, redant_libs/support_libs/relog.py, redant_test_main.py, redant_test_runner.py, requirements.txt, runner_thread.py, test_list_builder.py, tests/example/sample_component/test_sample.py, tests/parent_test.py
1. Logging class cleaned up.
2. Logging of TCs in their respective log files.
3. The logging dir structure resembles the TC
structure.
4. Added flag for specific test run but not
handled.
5. Test run based on multiple volume types
handled.
6. Output of redant_test_runner improved.
Fixes: #121
=> Logging re-structurized

parsing/CONFIG_README.md, parsing/config.yml, parsing/redant_params_handler.py
Underscore is replaced by hiphen in hostname
Fixes: #132
=> Underscore is removed from hostname

README.md
The flag was missing in the readme to run a single test case. Added `-c`.
Fixes: #142
=> Command for running single TC modified

core/test_list_builder.py
Now one, user can even push non volume TCs, i.e.
TC won't require to be linked to any particular
volume type. This leads to two scenarios,
1. A TC which doesn't even create volumes.
2. A TC which might go one to deal with
volumes of multiple times at a time.
Fixes: #162
=> Handle non volume TCs.

support/ops/gluster_ops/gluster_ops.py, tests/functional/glusterd/test_glusterd_start_stop.py
Following code changes have been handled:
1. Addition of reset-failed feature to
handle burst limit issue in glusterd.
2. Gluster ops functions enhanced
to handle multi server operations.
3. Two new functions added
3.1 wait_for_glusterd_to_start
3.2 get_gluster_version
Fixes: #161, #163
=> Gluster-ops enhancement

support/ops/gluster_ops/gluster_ops.py, support/ops/gluster_ops/peer_ops.py, support/ops/gluster_ops/volume_ops.py, support/ops/support_ops/io_ops.py, support/ops/support_ops/relog.py, support/ops/support_ops/rexe.py
This seems to be related to the fact that the logger
takes in the function and line number values from
where it is being executed and hence we cannot
delegate and generalize the logger functions by
calling them from a common location.
This might be something which works in languages
which go through a good level of compilation steps
but the same is not done in python. Hence reverting back
to the pythonic way of logging.
Fixes: #167
=> Logger doesn't reflect proper module and line number

support/ops/support_ops/rexe.py, tests/functional/glusterd/test_peer_probe_detach.py, tests/functional/glusterd/test_volume_create_delete.py
The test cases are failing because the latest changes
in the framework have not been incorporated in them.
Especially with start_glusterd and stop_glusterd.
Fixes: #169
=> [Testfix] Test failing with erraneous function calls.

core/parsing/params_handler.py, core/redant_main.py, core/result_handler.py, core/runner_thread.py, core/test_list_builder.py, requirements.txt, support/ops/gluster_ops/gluster_ops.py, support/ops/gluster_ops/peer_ops.py, support/ops/gluster_ops/volume_ops.py, support/ops/support_ops/io_ops.py, support/relog.py, support/rexe.py, tests/example/sample_component/test_file_creation.py, tests/example/sample_component/test_sample.py, tests/functional/glusterd/test_glusterd_start_stop.py, tests/functional/glusterd/test_peer_probe_detach.py, tests/functional/glusterd/test_volume_create_delete.py, tests/parent_test.py
Ops libraries can now run commands on any of the
connected nodes when the node list or node isn't
provided.
Multipledispatch has been added to dependency
to handle function overloading in Rexe.
Also, the execute command and multinode functions
have inverted order of parameter. The first param
being `cmd` and the second being `node` ( For
functions which take node ).
Fixes: #144
=> [Lib] Adding random execution handling in Rexe.

common/ops/abstract_ops.py, common/ops/gluster_ops/volume_ops.py, core/environ.py, core/parsing/params_handler.py, core/redant_main.py, core/runner_thread.py, core/test_runner.py, tests/example/sample_component/test_file_creation.py, tests/example/sample_component/test_sample.py, tests/example/sample_component/test_vol_creation.py, tests/parent_test.py
Multiple code changes:
1. Volume creation method modified to handle replica,
distributed and distributed-replica volume with servers
having single brick root.
2. Param handler methods converted from class methods to
regular methods so that gc doesn't do a cleanup after
object goes out of scope.
Fixes: #209
Updates: #186
=> Volume creation in parent test and param handler changes

core/redant_main.py, core/result_handler.py, core/test_runner.py
The current implementation will have a bottleneck because of
the nature of how threads are executed in python, wherein threads
and the main process share the GIL even though the system might
boast of multiple processor cores.
To work around this bottleneck in python, multiprocessing module
can be used. Now one can argue that multiprocess will create a
separate process in the background and that this will be heavier than
a thread and also would consume more time than spinning up a new thread.
To solve this, we use the idea of worker processes taking up tasks from
a queue, hence processes are spun up once and are killed only when there
is no job in the queue.
One more point to note is that the multiprocessing requires some mechanism of
locking to prevent the main process form going ahead …
=> Converting threading to multiprocessing

common/rexe.py
Added the passwordless ssh code in the remote executioner. Now no user
name or password is required. To test the same you need to setup the
passwordless ssh on your servers.
Note: Setup passwordless ssh from one server to another server and from
one server to the same server as well.
Fixes: #154
=> Added the passwordless ssh code in rexe

config/CONFIG_README.md, config/config.yml
username and password for the nodes are removed from the config file
as they are redundant after incorporating passwordless ssh into the
test framework.
Fixes: #240
=> User credentials are removed from config file

core/runner_thread.py, core/test_runner.py, tests/parent_test.py
Gluster Operations are shifted from constructor of parent test to
parent_test_run under the try-except clause
Fixes: #239
=> Gluster Operations shifted from parent test constructor to parent_test_run

common/rexe.py
The current set of features don't support async behaviour
and for the ops and tests to grow, this is a natural
extension. Async uses the same set of base libraries
as that of sync command execution.
Fixes: #248
=> Adding async capabilities in rexe.

common/rexe.py, core/environ.py, tests/functional/glusterd/test_glusterd_start_stop.py
Previously, on shutdown or connection failure a stact traceback was
displayed. Instead, a simple message is being displayed in its place
now.
Fixes: #236
=> Added message to handle connection failure

common/ops/gluster_ops/volume_ops.py, config/config.yml, tests/example/sample_component/test_vol_creation.py
In volume ops, inside volume create added arbiter option to take care of
arbiter volume types.
Fixes: #260
=> Added arbiter option in volume create

common/ops/abstract_ops.py
Abstract_ops_multinode needs to check the error code for each ret
returned. If it fails in any case the exception has to be raised.
Fixes: #258
=> Modified abstract ops multinode

common/ops/gluster_ops/gluster_ops.py
Gluster ops was showing success messages in the logs which were not
necessary as mentioned in #250.
Fixes: #272
=> Removed success messages from gluster ops

README.md, docs/RP/HLD.md, tests/README.md, tests/abstract_test.py, tests/example/sample_component/test_sample.py, tests/example/sample_component/test_vol_creation.py, tests/functional/glusterd/test_glusterd_start_stop.py
The name parent test was very misleading as it was not exactly parent
but actually all the tests are abstracting the Parent test. Hence, this
confusion needs to be removed with a better nomenclature and the name
came upon with is Abstrat Test as it desccribes the class
straightforward.
Updates: #286
=> Changed parent test to abstract test

tools/linting.sh
Lint script changed as per the recent commits pushed. Now, anyone can
test the lint by just running `tools/linting.sh -f -l` and both flake
and pylint will run and provide results similar to the check that take
place through linting.yaml
Fixes: #287
=> Lint script modified

common/ops/gluster_ops/volume_ops.py, tests/functional/glusterd/test_glusterd_set_reset_reserve_limit.py
The test case is concerned with reserve limit option in a volume.
Following set of operations are performed,
1. Set storage reserve limit to some value
2. validate it
3. Reset it
4. Validate if it is reset properly.
#Updates: #292
Signed-off-by: srijan-sivakumar ssivakum@redhat.com
=> [Test] Test glusterd set reset reserve limit

tests/functional/glusterd/test_default_max_bricks_per_process.py
Migrated the [test from glusto-tests](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_default_max_bricks_per_process.py)
Made changes as per the functionalities in redant.
Updates : #292
Fixes : #305
=> Added test_default_max_bricks_per_process

tests/functional/glusterd/test_glusterd_quorum_command.py
Glusto test link : [test_glusterd_quorum_command](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_quorum_command.py)
Fixes: #308
=> [Test] test_glusterd_quorum_command migration

tests/functional/glusterd/test_enable_storage_reserve_volume.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_enable_storage_reserve_volume.py)
Modified as per the ops in redant.
Updates : #292
Fixes : #313
=> Added test_enable_storage_reserve_volume

common/relog.py, core/redant_main.py, core/test_list_builder.py, core/test_runner.py
1. Reduced the convoluted way of log dir creation.
2. The tuple being sent back from test list builder replaced
with a simple dictionary.
3. Removed the excluded tests print from test_runner.
Fixes: #314
=> [Core][Common] Log dir creation and test list

common/ops/support_ops/io_ops.py, tests/functional/glusterd/test_op_version.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_op_version.py).
Modified the same using the ops in redant
Updates: #292
Fixes: #323
=> Added test_op_version

common/ops/support_ops/io_ops.py, tests/abstract_test.py, tests/example/sample_component/test_sample.py, tests/functional/glusterd/test_io.py
execute_io_cmd from io_ops is removed and all the function calls
are replaced by execute_abstract_op_node.
Fixes: #340
=> execute_io_cmd is removed

tests/functional/glusterd/test_lower_gluster_op_version.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_lower_gluster_op_version.py).
Modified it as per the ops in redant.
Updates: #292
Fixes: #339
=> Migrated test_lower_gluster_op_version

tests/functional/glusterd/test_glusterd_logs_when_peer_detach.py
[test_glusterd_logs_when_peer_detach.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_logs_when_peer_detach.py) is migrated to redant
Updates: #292
Fixes: #317  
=> Migration of test_glusterd_logs_when_peer_detach

tests/functional/glusterd/test_glusterd_selinux.py
[test_glusterd_selinux.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_selinux.py) test case is migrated to redant
Updates: #292
Fixes: #334 
=> Migration of test_glusterd_selinux

tests/functional/glusterd/test_add_remove_brick.py
In the test_add_remove_brick, try and except clause was explicitly been
called and hence there was no traceback getting generated in the logs if
the test was failing. This is handled now by removing the try except
from the test.
Fixes: #342
=> Fixed test_add_remove_brick issue

common/ops/gluster_ops/gluster_ops.py, tests/functional/glusterd/test_setting_volume_level_option_to_cluster.py
Added the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_setting_volume_level_option_to_cluster.py).
Made modifications as per the ops in redant.
Updates: #292
Fixes: #345
=> Migrated test_setting_volume_level_option_to_cluster

tests/example/sample_component/test_add_remove_brick.py, tests/example/sample_component/test_io.py
Following cases,
1. test_add_remove_brick
2. test_io
are migrated to example/sample_component.
Fixes: #360
=> [Tests] Moved tests from glusterd to example

tools/migrate_tc.py
The migration script is now able to handle the
operation of automatically doing the migration of a
test case from glusto to redant with history.
What isn't done is the modifications in the said test file.
This change, i.e. automated script changes will be part
of subsequent PRs.
Updates: #364
=> [Tools] Migration Script

tests/functional/glusterd/test_ops_when_one_node_is_down.py
Added the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_ops_when_one_node_is_down.py).
Made modifications as per the ops.
Updates: #292
Fixes: #348
=> Migrated test_ops_when_one_node_is_down

tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
[test_gluster_volume_status_xml_dump.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_gluster_volume_status_xml_dump.py) test case is migrated to redant.
Updates: #292
Fixes: #335 
=> Migration of test_gluster_volume_status_xml_dump

common/mixin.py, common/ops/gluster_ops/brick_ops.py, common/ops/gluster_ops/peer_ops.py, common/ops/gluster_ops/volume_ops.py, core/environ.py, tests/functional/glusterd/test_probe_hostname.py
1. Migrated the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_probe_hostname.py).
2. Added form_brick_cmd in brick ops to reuse the function wherever
needed. Used the same in the volume_crete part.
3. Modified peer_ops: Peer probe return type was wrong as it was returning boolean. Hence changed from dict to bool and modified the docstring.
Updates: #292
Fixes: #371
=> Migrated test_probe_hostname and added form_brick_cmd in brick ops

common/ops/gluster_ops/peer_ops.py, tests/functional/glusterd/test_profile_start_with_quorum_not_met.py
Migrated the [test case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_profile_start_with_quorum_not_met.py).
Added validate_peer_is_connected in peer ops. It's originally in Gluster
Base class in glusto-tests.
Updates: #292
Fixes: #387
=> Migrated test_profile_start_with_quorum_not_met

tests/functional/glusterd/test_volume_status_xml.py
The check for error logs in the glusterd
has been removed as the glusterd does throw
a harmless Error log saying volume is not started
when someone tries to query status when the
volume isn't started.
Fixes: #401
=> [Test] Migration of test_volume_status_xml

common/ops/abstract_ops.py, common/ops/gluster_ops/volume_ops.py
In case the volume_status command is success, the volume status is
returned. In case the volume status command has failed then the
exception is bypassed and the ret value from abstract ops is
returned.
Fixes: #367
=> Adding excep flag to bypass exception

core/environ.py, tests/d_parent_test.py
In case of disruptive TC if the test_case fails midway then
the volumes created in the tc are deleted
Fixes: #418
=> Cleanup of volumes creates in test case in disruptive tc

common/ops/gluster_ops/brick_ops.py, common/ops/gluster_ops/volume_ops.py, core/environ.py, tests/d_parent_test.py, tests/functional/glusterd/test_enable_storage_reserve_volume.py, tests/lazy_parent_test.py, tests/nd_parent_test.py, tests/vol_destroy_test.py
Sanitize and cleanup functionalities added.
1. The volume sanitize is used for prepping a volume for the next TC or even to be used within a test case.
2. The volume cleanup is to be used for complete cleanup of volume and its mount.
Also added is the brick dir deletion which is handled at
1. nd_parent_test
2. d_parent_test
3. vol_destroy_test
Fixes: #408
=> [Core][Common][Test] Sanitize and cleanup

core/test_runner.py
Generic loop won't be started unless and until
there's a generic TC present.
Fixes: #431
=> [Core] Check for generic test

common/ops/gluster_ops/volume_ops.py, tests/functional/glusterd/test_host_uuid_in_volume_info_xml.py
Migration of [test_case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_host_uuid_in_volume_info_xml.py) from glusto to redant
Updates: #292
Fixes: #446 
=> Migration of test_host_uuid_in_volume_info_xml.py

tests/functional/glusterd/test_default_ping_timer_and_epoll_thread_count.py
Migrated the [test case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_default_ping_timer_and_epoll_thread_count.py)
Added the redant functionalities wherever needed.
Updates : #292
Fixes : #309
=> Added test_default_ping_timer_and_epoll_thread_count

tests/functional/glusterd/test_validate_auth_allow_and_auth_reject.py
Migrated the
[test_case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_validate_auth_allow_and_auth_reject.py).
Updates: #292
Fixes: #409
=> Migrated test_validate_auth_allow_and_auth_reject

tests/functional/glusterd/test_default_ping_timer_and_epoll_thread_count.py
Modified the [test
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_default_ping_timer_and_epoll_thread_count.py)
Updates: #292
=> Modified the test_default_piing_timer_and_epoll_thread_count

common/ops/gluster_ops/volume_ops.py, core/environ.py, tests/d_parent_test.py
This fix is aimed towards handling the mount point
data structure handling which was adding same paths multiple
times and also added the traceback in d_parent_test
teardown.
Fixes: #453
=> [Core][Test] d_parent_handling and mount ds fix

common/ops/gluster_ops/brick_ops.py, core/environ.py, docs/BP/Ops/brick_ops.md, tests/functional/glusterd/test_add_brick_when_quorum_not_met.py
Migrated the [test case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_add_brick_when_quorum_not_met.py).
Added `are_bricks_offline` in brick ops.
Updates: #292
Fixes: #352
=> Migrated test_add_brick_when_quorum_not_met

common/ops/support_ops/io_ops.py, tests/functional/glusterd/test_readonly_option_on_volume.py
Test migration :  [test_readonly_option_on_volume](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_readonly_option_on_volume.py)
Fixes: #403
=> [Test] Migrating test_readonly_option_on_volume

tests/functional/glusterd/test_add_brick_when_quorum_not_met.py
* Replaced the logic for wait_for_glusterd_to_stop with the pre-existing
function.
* Added the last part of the test case in the terminate.
Fixes: #459
=> Changes in test_add_brick_when_quorum_not_met

tests/functional/glusterd/test_remove_brick_when_quorum_not_met.py
Migrated the [test case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_remove_brick_when_quorum_not_met.py). Made modifications as per the redant standards.
Updates: #292
Fixes: #411
=> Added test_remove_brick_when_quorum_not_met

tests/functional/glusterd/test_brick_port_after_stop_glusterd_modify_volume.py
terminate funtionalities are added in try except and self.gusterd_stopped class variable is removed
Fixes: #463
=> terminate funtionalities are added in try except

common/ops/gluster_ops/volume_ops.py, common/ops/support_ops/io_ops.py
The mount cleanup is not done properly due to some corner cases
1. When the mountpount is already unmounted
2. When the mountpoint is unmount and deleted
And this is done in such a manner that the update escapes the data structure itself.
Fixes: #467
=> Mount cleanup corner case handling

tests/functional/glusterd/test_default_ping_timer_and_epoll_thread_count.py
In test_default_ping_timer_and_epoll_thread_count, the path needs to be
changed.
Fixes: #470
=> Change path of glusterd.vol in the test

common/ops/gluster_ops/peer_ops.py, common/ops/gluster_ops/volume_ops.py, tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
Migrated the TC [test_volume_set_with_quorum_enabled](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_set_with_quorum_enabled.py)
Fixes: #457 
Updates: #292
=> Migrated TC test_volume_set_with_quorum_enabled

common/ops/gluster_ops/volume_ops.py, core/environ.py, tests/d_parent_test.py, tests/functional/glusterd/test_peer_probe.py, tests/vol_destroy_test.py
Migration of the [test case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_peer_probe.py) is done from glusto to redant.
cleanup volume now takes a single node as parameter on which
the command has to run unlike list of servers like before. Accordingly
changes are done to all the calls to cleanup_volume
Updates: #292
Fixes: #452
=> Migration of test_peer_probe and changes to cleanup_volume

.pylintrc, common/ops/support_ops/io_ops.py, tests/functional/glusterd/test_probe_glusterd.py
Added the function check_core_file_exists.
Migrated the [test case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_probe_glusterd.py) and made modifications as per the ops in redant.
Update: #292
Fixes: #319 
Fixes: #359
=> Added check_core_file_exists and test_probe_glusterd

tests/functional/glusterd/test_gluster_volume_status_xml_dump.py
test_gluster_volume_status_xml_dump has
spurious failure which is happening because
we are not waiting for a volume to stop before
going on with our other operations.
Fixes: #483
=> [Test] Fixing spurious failure in TC.

common/ops/gluster_ops/peer_ops.py, tests/functional/glusterd/test_quorum_syslog.py
Migrated TC [test_quorum_syslog](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_quorum_syslog.py)
Fixes: #499 
Updates: #292 
=> Migrated TC test_quorum_syslog

common/ops/gluster_ops/profile_ops.py, common/ops/gluster_ops/volume_ops.py, tests/functional/glusterd/test_profile_operations.py
Migrated TC [test_profile_operations](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_profile_operations.py) and merged TC [test_profile_info_without_having_profile_started](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_profile_info_without_having_profile_started.py) into it.
Fixes: #486 and Fixes: #487 
Updates: #292 
=> Migrated TC test_profile_operations

common/ops/gluster_ops/peer_ops.py, tests/d_parent_test.py, tests/functional/glusterd/test_brick_port_after_stop_glusterd_modify_volume.py, tests/functional/glusterd/test_ops_when_one_node_is_down.py, tests/functional/glusterd/test_peer_detach.py, tests/functional/glusterd/test_peer_probe.py, tests/functional/glusterd/test_probe_glusterd.py, tests/functional/glusterd/test_probe_hostname.py, tests/functional/glusterd/test_setting_volume_level_option_to_cluster.py, tests/functional/glusterd/test_validate_peer_probe_ip_fqdn_hostname.py, tests/nd_parent_test.py
Migrated TC [test_peer_detach](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_peer_detach.py)
Also, added the ops `peer_probe_servers` and `peer_detach_servers`.
Updated the peer ops to follow the same pattern of params declaration, i.e, first the list/str of servers and then the node to perform the operation.
Fixes: #505 and Fixes: #480
Updates: #292 
=> Migrated TC test_peer_detach

tests/functional/glusterd/test_volume_set_when_glusterd_stopped_on_one_node.py
Remove the none check from the `get_online_bricks_list` return value so as to consider the race scenario while starting a volume immediately after the glusterd start.
=> TestFix: Remove the None check for volume_status

common/mixin.py, common/ops/gluster_ops/brick_ops.py, common/ops/gluster_ops/gluster_ops.py, common/ops/gluster_ops/heal_ops.py, common/ops/gluster_ops/peer_ops.py, common/ops/gluster_ops/volume_ops.py, core/environ.py, tests/functional/glusterd/test_glusterd_default_volume_behavior_quorum_options.py
Migrated TC [test_glusterd_default_volume_behaviour_quorum_options](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_default_volume_behavior_quorum_options.py)
And, added brick and volume ops.
Fixes: #511 and Fixes: #516 
Updates: #292 
=> Migrated TC test_glusterd_default_volume_behaviour_quorum_options

tests/functional/glusterd/test_concurrent_set.py
Migrating [test_case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_concurrent_set.py) from glusto to redant
Updates: #292
Fixes: #420 
=> Migrating test_concurrent_set.py from glusto to redant

tests/functional/glusterd/test_rebalance_new_node.py
Migration of [test_rebalance_new_node.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_rebalance_new_node.py) from glusto to redant
Fixes: #292
Fixes: #492
=> Migration of test_rebalance_new_node.py from glusto to redant

tests/functional/glusterd/test_glusterd_restart_quorum_not_met.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_glusterd_restart_quorum_not_met.py)
Updates: #292
Fixes: #528
=> Migrated test_glusterd_restart_quorum_not_met

common/ops/gluster_ops/brick_ops.py, core/parsing/params_handler.py, tests/functional/glusterd/test_volume_status_show_bricks_online_though_brickpath_deleted.py
Migrated TC [test_volume_status_show_bricks_online_though_brickpath_deleted](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_status_show_bricks_online_though_brickpath_deleted.py)
Also, added the op `are_bricks_online`
Fixes: #534 
Updates: #292 
=> Migrated TC test_volume_status_show_bricks_online_though_brickpath_deleted

common/ops/gluster_ops/volume_ops.py, tests/functional/glusterd/test_xml_dump_of_gluster_volume_status_during_rebalance.py
[test case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_xml_dump_of_gluster_volume_status_during_rebalance.py) is migrated from glusto to redant and get_volume_status is modified in volume_ops to accomodate the tasks option in status
Updates: #292
Fixes: #536
=> Migration of test_xml_dump_of_gluster_volume_status_during_rebalance

tests/functional/glusterd/test_create_vol_with_used_bricks.py
Migrated the [test case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_create_vol_with_used_bricks.py) from the glusto-test and made changes as per the
functionalities in redant.
Updates: #292
Fixes: #300
=> Added test_create_vol_with_used_bricks

tests/functional/glusterd/test_volume_set_with_quorum_enabled.py
Traceback has nothing called format_exec. It is format_exc
=> Changing traceback fn call

tests/functional/glusterd/test_peer_status.py
Migration of [test_case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_peer_status.py) from glusto to redant
Updates: #292
Fixes: #552
=> Migration of test_peer_status

common/ops/gluster_ops/volume_ops.py, tests/d_parent_test.py, tests/functional/glusterd/test_glusterd_quorum.py
Migrated TC [test_glusterd_quorum](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_quorum.py)
Also, adds a `setup_test` abstract method for disruptive TCs, to
allow setup volumes in the TC and not in the parent_run_test itself.
Fixes: #553 
Updates: #292 
=> Migrated test_glusterd_quorum TC

common/ops/gluster_ops/peer_ops.py, tests/functional/glusterd/test_peer_detach.py, tests/functional/glusterd/test_peer_status.py, tests/functional/glusterd/test_probe_hostname.py
Fix:
Peer probe and detach operation updates the `opRet` and `opErrstr` value instead of
the `error_code` and `error_msg`, so updated the Tcs and the ops accordingly.
Fixes: #573 
=> Fix: Peer probe and detach TCs to check for 'opRet' value

tests/functional/glusterd/test_rebalance_when_quorum_not_met.py
The key value is `task_status` and not `task`.
Fixes: #575
=> [Testfix] Changing the key value

common/ops/gluster_ops/brick_ops.py, common/ops/gluster_ops/volume_ops.py, tests/example/sample_component/test_brick_ops.py, tests/functional/glusterd/test_add_brick_when_quorum_not_met.py, tests/functional/glusterd/test_create_vol_with_used_bricks.py, tests/functional/glusterd/test_glusterd_replace_brick.py, tests/functional/glusterd/test_peer_status.py, tests/functional/glusterd/test_probe_hostname.py, tests/functional/glusterd/test_rebalance_new_node.py
Migrated TC [test_glusterd_remove_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_replace_brick.py)
Also, added the `replace_brick_from_volume` op.
Fixes: #559 
Updates: #292 
=> Migrated TC test_glusterd_replace_brick

tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py)
Updates: #292
Fixes: #560
=>  Migrated test_enable_brickmux_create_and_stop_three_volumes

common/ops/support_ops/io_ops.py, tests/functional/glusterd/test_mount_after_removing_client_logs_dir.py
Migrated TC [test_mount_after_removing_client_logs_dir](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_mount_after_removing_client_logs_dir.py)
Fixes: #558 
Updates: #292 
=> Migrated test_mount_after_removing_client_logs_dir

tests/example/sample_component/test_profile_ops.py, tests/functional/glusterd/test_profile_operations_with_one_node_down.py
case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_profile_operations_with_one_node_down.py)
Updates: #292
Fixes: #412
=> Migrated test_profile_operations_with_one_node_down

tests/functional/glusterd/test_replace_brick_quorum_not_met.py
Migrated TC [test_replace_brick_quorum_not_met](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_replace_brick_quorum_not_met.py)
Fixes: #595 
Updates: #292 
=> Migrated test_replace_brick_quorum_not_met

tests/functional/glusterd/test_glusterd_split_brain.py
Migrated TC [test_glusterd_split_brain](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_split_brain.py)
Fixes: #588 
Updates: #292 
=> Migrated test_glusterd_split_brain

tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py
Migrating [test_reserve_limt_change_while_rebalance.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_reserve_limt_change_while_rebalance.py) from glusto to redant.             
Updates: #292:                                                                  
Fixes: #585                                                                                                            
=> Migrating test_reserve_limt_change_while_rebalance.py  

tests/functional/glusterd/test_reserved_port_range_for_gluster.py
Migrated the [test case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_reserved_port_range_for_gluster.py)
Fixes: #410
Updates: #292
=> Migrated test_reserved_port_range_for_gluster

config/config.yml, tests/functional/glusterd/test_probe_hostname.py
Added the terminate function to perform
a hard termiate so as to prevent the probe
issues coming up later because of the hostname
and IP issue.
Fixes: #601
=> [TestFix] Fixing test_probe_hostname

tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py)
Updates: #292
Fixes: #447
=> Migrate test_volume_create_with_glusterd_restarts

common/ops/gluster_ops/volume_ops.py, tests/functional/glusterd/test_volume_status_with_absent_bricks.py
Migrated [test case](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_status_with_absent_bricks.py)
Updates: #465 
=> Migration of test_volume_status_with_absent_bricks

tests/functional/glusterd/test_volume_status_with_absent_bricks.py
Fixed the condition. Replaced `error_code` with `['msg']['opRet']`.
Fixes: #608
=> Fixed condition in test_volume_status_with_absent_bricks

common/ops/support_ops/io_ops.py, tests/functional/glusterd/test_mountpoint_ownership_post_volume_restart.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_mountpoint_ownership_post_volume_restart.py)
Updates: #292
Fixes: #581
=> Migrated test_mountpoint_ownership_post_volume_restart

common/ops/gluster_ops/brick_ops.py, common/ops/gluster_ops/gluster_ops.py, common/ops/gluster_ops/heal_ops.py, common/ops/gluster_ops/mount_ops.py, common/ops/gluster_ops/peer_ops.py, common/ops/gluster_ops/profile_ops.py, common/ops/gluster_ops/rebalance_ops.py, common/ops/gluster_ops/volume_ops.py
* At various places, excep flag was mentioning `volume status command fails` even when the function was carrying out something else.
* Are bricks online had offline in place of online
* Mount Ops' wrong  class description fixed
* Fixed a few grammatical mistakes.
=> Fixed docstrings

core/test_runner.py
Why to create and destroy workers when we can
make do with the pre-existing workers
available with non disruptive cases. So we simply let
the worker dip their hands on the generic nd queue
when they find volume queue to be empty.
Fixes: #617
=> [Core] Simplifying the Worker job handling

common/mixin.py, common/ops/gluster_ops/shared_storage_ops.py, tests/functional/glusterd/test_glusterd_split_brain.py, tests/functional/glusterd/test_shared_storage.py
Migrated TC [test_shared_storage](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_shared_storage.py)
Added `shared_storage_ops`
Fixes: #609 , and Fixes: #610 
Updates: #292 
=> Added shared storage ops and migrate a TC

tests/functional/glusterd/test_bricks_online_after_node_reboot.py
Migration of [test_bricks_online_after_node_reboot.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_bricks_online_after_node_reboot.py) from glusto to redant.
Updates: #292
Fixes: #605
=> Migration of test_bricks_online_after_node_reboot.py

common/ops/gluster_ops/mount_ops.py, tests/functional/glusterd/test_mountpoint_ownership_post_volume_restart.py
In test_mountpoint_ownership_post_volume_restart the mountpoint on
client was failing to connect. Now there weretwo fixes:
1. Add a sleep(3) and it was perfectly working
2. create a function that can handle the same in every condition
So added a function to take care of the same and for all kinds of VMs.
Fixes: #616
=> Fixed mountpoint connection failure in test

tests/functional/glusterd/test_add_identical_brick_new_node.py
Migrating [test_add_identical_brick_new_node.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_add_identical_brick_new_node.py) from glusto to redant
Updates: #292
Fixes: #598
=> Migrating test_add_identical_brick_new_node.py

tests/functional/glusterd/test_status_string_in_volstatus.py
Migration of [test_status_string_in_volstatus.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_status_string_in_volstatus.py) from glusto to redant
Updates: #292
Fixes: #625
=> Migration of test_status_string_in_volstatus.py

tests/functional/glusterd/test_setting_volume_option_when_one_node_is_down_in_cluster.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_setting_volume_option_when_one_node_is_down_in_cluster.py)
Updates: #292
Fixes: #555
=> Migrated test_setting_volume_option_when_one_node_is_down_in_cluster

common/ops/support_ops/machine_ops.py
The method being invoked in machine ops functions is `check_power_node_status` while the actual name of the method is `check_node_power_status`
Fixes: #635 
Signed-off-by: srijan-sivakmuar ssivakum@redhat.com
=> [Common] Correcting function invocation name

tests/functional/glusterd/test_setting_volume_option_with_more_than_4096_characters.py
Migration of [test_setting_volume_option_with_more_than_4096_characters.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_setting_volume_option_with_more_than_4096_characters.py) test case
Updates: #292
Fixes: #353
=> Migration of test_setting_volume_option_with_more_than_4096_characters

config/config.yml, tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py
Migrated TC [test_peer_probe_firewall_ports_not_opened](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py)
Fixes: #429 
Updates: #292 
=> Migrated TC test_peer_probe_firewall_ports_not_opened

common/ops/support_ops/machine_ops.py, tests/functional/glusterd/test_probe_glusterd_down.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_probe_glusterd_down.py)
Updates: #292
Fixes: #582
=> Migrated test_probe_glusterd_down

tests/functional/glusterd/test_gluster_detect_drop_of_outbound_traffic.py, tests/functional/glusterd/test_volume_create.py
Migration of [test_volume_create.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_create.py) from glusto to redant
Updates: #292
Fixes: #562 
=> Migration of test_volume_create.py

common/ops/gluster_ops/peer_ops.py, common/rexe.py, tests/functional/glusterd/test_peer_detach_check_warning_message.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_peer_detach_check_warning_message.py)
Updates: #292
Fixes: #356
=> Migrated test_peer_detach_check_warning_message

common/ops/support_ops/machine_ops.py
Sometimes, the unmount will fail causing the mountpoint to not to be deleted. Hence changing the bash logic.
=> Changing conditional bash from and

tests/functional/glusterd/test_enable_brickmux_create_and_stop_three_volumes.py
Fix:
The brick mux option was set after the volumes in the list were created for each test run.
But, the test case doesn't require the test case to create pre-created volumes, rather
create volumes within the test case and check for the process count for the bricks for each volume
accordingly.
=> TestFix: Made the test generic and fixed the process count check

README.md, core/redant_main.py
`sp` flag is removed from the Argument Parser. The same is handled using
a condition.
Fixes: #665
=> Removed sp flag

common/ops/gluster_ops/volume_ops.py, common/ops/support_ops/machine_ops.py, tests/functional/glusterd/test_brickmux_brick_process.py
case](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/glusterd/test_brickmux_brick_process.py)
Added are_nodes_online.
Fixes: #685
=> Migrated test_brickmux_brick_process

common/ops/gluster_ops/volume_ops.py, tests/functional/glusterd/test_brickmux_brick_process.py, tests/functional/glusterd/test_glusterd_memory_consumption_increase.py
The excep flag should not be hardcoded. It should be
left to the user to pass the excep flag to the
bulk_vol_create function so as to be used further
in setup_volume.
Fixes: #711
=> [Common] Fix bulk volume create

core/result_handler.py, core/runner_thread.py, core/test_runner.py, tests/d_parent_test.py, tests/functional/glusterd/test_create_vol_with_used_bricks.py, tests/functional/glusterd/test_gluster_does_not_do_posix_lock_when_multiple_client.py, tests/functional/glusterd/test_glusterd_quorum.py, tests/functional/glusterd/test_glusterd_split_brain.py, tests/functional/glusterd/test_volume_create.py, tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py, tests/functional/glusterd/test_volume_status_show_bricks_online_though_brickpath_deleted.py, tests/nd_parent_test.py
Certain test cases have a minimum requirement of
server and client machines which cannot be expected
to be furnished by all the users running the complete
suite. Hence those tests have a conditional check
at the very beginning of the TC to prevent test from
even running. But the current flow is to mark those
tests as failed. This is un-necessary and also
not logical as those tests were not even run
because of inadequate resources provided by the user.
Hence introducing another category called `Skipped`
tests which will be considered as run tests but it'll
be shown to the user that these tests have been skipped
and also the result computation won't consider these
tests into the calculation. Along with the state and
time taken to run, the results will contain the skip
reason to cater the …
=> [Core][Test] Skip conditional in test

core/result_handler.py
xlsx writter cannot accept a exception as an input
hence converting it into string before pushing the
skip reason.
Fixes: #727
=> [Core] XLS exception handling

common/ops/gluster_ops/mount_ops.py
The mount command is modified
from `mount -t glusterfs` to
`mount.glusterfs` as the mount script
is sometimes not added to path.
Desciption:
Fixes: #676
=> Modifying mount command

core/result_handler.py
The skip count took into account the total
subtest skips and hence the data outputted
was more than what was expected. This fix
changes how the count is aggregated.
Secondly, the time output was messing up whenever
the minute or hour wasn't an integer. Hence setting
them to int.
Updates: #719
=> [Result] Fixing skip count and time output

tests/d_parent_test.py, tests/functional/glusterd/test_get_state_on_brick_unmount.py, tests/functional/glusterd/test_glusterd_quorum.py, tests/functional/glusterd/test_mount_after_removing_client_logs_dir.py, tests/functional/glusterd/test_peer_probe_firewall_ports_not_opened.py, tests/functional/glusterd/test_replace_brick_quorum_not_met.py, tests/functional/glusterd/test_setting_volume_option_when_one_node_is_down_in_cluster.py, tests/functional/glusterd/test_volume_create_with_glusterd_restarts.py, tests/functional/glusterd/test_volume_operations.py
The current custom setup requires that the
setup custom variable is set. But this puts
the onus on to the user to properly know the variable
and use it. But this can be replaced with a decorator.
Now this decorator could be further used to define
what the parent itself is supposed to do.
There are many a cases wherein cluster is not required
from the parent and even a volume is not needed
in the started state. This can be controlled
with the help of arguments passed to the decorator
and eventually used in the parent while the setup
is going on.
Fixes: #742
=> [Test] Custom setup invoked with decorator.

common/ops/support_ops/io_ops.py, tests/functional/glusterd/test_detach_node_used_to_mount.py
Migration of [test_detach_node_used_to_mount.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_detach_node_used_to_mount.py) from glusto to redant.
get_fattr_list function is added in the io_ops which is needed in the test case.
Updates: #292
Fixes: #626
=> Migration of test_detach_node_used_to_mount.py

tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py
Migrated TC [test_glusterd_statedump_with_server_client_quorum](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_statedump_with_server_and_client_quorum_set.py)
Fixes: #741 
Updates: #292 
=> Migrated TC test_glusterd_statedump_with_server_client_quorum

common/ops/gluster_ops/brick_ops.py, tests/example/sample_component/test_brick_ops.py
The form brick cmd is not suitable for replace brick. Let's suppose if a test case demands multiple bricks to replace, then in that  case the following code:
```python
if add_flag:
brick_list = self.get_all_bricks(volname, server_list[0])
last_brick_num = int(brick_list[-1].split('-')[-1])
iter_add = len(brick_list)
if last_brick_num >= iter_add:
iter_add += 1
```
This will create the same brick always as the replace brick doesn't change the length of the brick_list. In that case, even if we had 0,1, 2 as the brick numbers. For the first replace it will work fine and we will have 3,1,2 but for the second replace it will again try to replace brick with 3 as the length is the same and the last brick is still 2.
Hence added a loop to get the max number of brick in the bricks list and
then …
=> Fixed form_brick_cmd and replace_brick_from_volume

common/ops/gluster_ops/brick_ops.py, common/ops/gluster_ops/volume_ops.py, core/environ.py, docs/BP/Ops/brick_ops.md, tests/nd_parent_test.py, tests/vol_destroy_test.py
Removed the cleands structure from the framework and let the deleting of
the bricks are handled when all the TCs are completed or if the volume
is cleaned-up.
Fixes: #765
=> [Core] Removed the usage of cleands structure in the framework

common/ops/support_ops/io_ops.py
Used f-strings in place of + in rmdir function.
=> Used f strings in rmdir

tests/functional/glusterfind/test_gfind_delete_cli.py
Migrated [TC test_gfind_delete_cli](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_delete_cli.py) from glusto
Updates: #292 
=> Test: Migrated TC test_gfind_delete_cli

tests/functional/glusterfind/test_gfind_list_cli.py
Migrated TC [test_gfind_list_cli](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_list_cli.py)
Updates: #292 
=> Migrated TC test_gfind_list_cli

tests/functional/glusterfind/test_gfind_query_cli.py
Migrated TC [test_gfind_query_cli](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_query_cli.pyhttps://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_gfind_query_cli.py)
Updates: #292 
=> Migrated TC test_gfind_query_cli

common/ops/gluster_ops/snapshot_ops.py, tests/functional/snapshot/test_activate_deactivate.py
The test case in glusto being,
[Test](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_activate_deactivate.py)
Updates: #292
=> [TestMigration] Migration of activate/deactivate snap test.

tests/functional/glusterfind/test_glusterfind_when_brick_down.py
Migrated TC [test_glusterfind_when_brick_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_glusterfind_when_brick_down.py)
Updates: #292 
=> Migrated TC test_glusterfind_when_brick_down.py

common/mixin.py, common/ops/gluster_ops/glusterd_ops.py, docs/BP/Ops/glusterd_ops.md
More of a nomenclature issue. Also reduces confusion
if any rises in future with the ops name.
Fixes: #807
=> [Common] Renaming gluster ops to glusterd ops.

common/ops/support_ops/machine_ops.py, tests/functional/glusterfind/test_gfind_delete_file.py, tests/functional/glusterfind/test_gfind_modify_files.py, tests/functional/glusterfind/test_gfind_rename.py, tests/functional/glusterfind/test_glusterfind_when_node_down.py
Migrated TC [test_glusterfind_when_node_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterfind/test_glusterfind_when_node_down.py)
Also, updated other TCs to add a sleep after pre-operation in case of file changes, as the changelog sometimes takes a bit of time to reflect the changes in the outfile.
Updates: #292 
=> Migrated TC test_glusterfind_when_node_down

common/ops/gluster_ops/auth_ops.py, tests/d_parent_test.py, tests/functional/authentication/test_auth_allow.py, tests/vol_create_test.py
Migrated TC [test_auth_allow](https://github.com/gluster/glusto-tests/blob/master/tests/functional/authentication/test_auth_allow.py)
Added few functions in auth_ops file, as they are resued in multiple auth TCs
Updates: #292 
=> Migrated TC test_auth_allow

common/ops/gluster_ops/volume_ops.py, tests/functional/authentication/test_authentication_allow_blank.py
Migrated TC [test_authentication_allow_blank](https://github.com/gluster/glusto-tests/blob/master/tests/functional/authentication/test_authentication_allow_blank.py)
Updates: #292 
=> Migrated TC test_authentication_allow_blank

tests/functional/authentication/test_auth_invalid_values.py
Migrated TC [test_auth_invalid_value](https://github.com/gluster/glusto-tests/blob/master/tests/functional/authentication/test_auth_invalid_values.py)
Updates: #292 
=> Migrated TC test_auth_invalid_value

common/ops/gluster_ops/glusterd_ops.py
Sometimes glusterd doesn't stop with systemctl
stop command, this causes the wait_till_glusterd_to_stop
to go on unable to do anything. Hence added an ungraceful
mechanism to handle this corner case in glusterd.
=> [Common] Glusterd ungraceful kill added.

common/ops/gluster_ops/heal_ops.py, tests/functional/afr/test_healed_and_heal_failed_command.py
Migrated
[test_healed_and_heal_failed_command](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_healed_and_heal_failed_command.py)
Updates: #292
=> Migrated test_healed_and_heal_failed_command

tests/functional/authentication/test_auth_allow_reject_same_client.py
Migrated TC [test_auth_allow_reject_same_client](https://github.com/gluster/glusto-tests/blob/master/tests/functional/authentication/test_auth_allow_reject_same_client.py)
Updates: #292 
=> Migrated TC test_auth_allow_reject_same_client

common/ops/gluster_ops/auth_ops.py, tests/functional/authentication/test_auth_reject_allow.py
Migrated TC [test_auth_reject_allow](https://github.com/gluster/glusto-tests/blob/master/tests/functional/authentication/test_auth_reject_allow.py)
Updates: #292 
=> Migrated TC test_auth_reject_allow

common/ops/gluster_ops/brick_ops.py, tests/functional/glusterd/test_quorum_remove_brick.py
Migrated TC [test_quorum_remove_brick](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_quorum_remove_brick.py)
Updates: #292 
=> Migrated TC test_quorum_remove_brick

common/ops/gluster_ops/volume_ops.py, tests/functional/glusterd/test_rebalance_start_not_failed_with_socket_path_too_long.py
Migrated TC [test_rebalance_start_not_failed_with_socker_path_too_long](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_rebalance_start_not_failed_with_socket_path_too_long.py)
Updates: #292 
=> Migrated TC test_rebalance_start_not_failed_with_socker_path_too_long

tests/functional/glusterd/test_glusterd_snap_info_on_detached_node.py
Migrate TC [test_glusterd_snap_info_on_detached_node](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_glusterd_snap_info_on_detached_node.py)
Updates: #292 
=> Migrate TC test_glusterd_snap_info_on_detached_node

tests/functional/glusterd/test_peer_probe_while_snapd_running.py
Migrate TC [test_peer_probe_while_snapd_running](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_peer_probe_while_snapd_running.py)
Updates: #292 
=> Migrate TC test_peer_probe_while_snapd_running

common/ops/support_ops/io_ops.py, tests/functional/glusterd/test_volume_network_ping_timeout.py
Migration of [test_volume_network_ping_timeout.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/glusterd/test_volume_network_ping_timeout.py)  from glusto to redant.                            
Updates: #292                                                                   
Fixes: #539                                                                                                         
=> Migration of test_volume_network_ping_timeout.py

tests/functional/arbiter/brick_cases/test_rmvrf_files.py
Migrated TC [test_rmvrf_files](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/brick_cases/test_rmvrf_files.py)
Updates: #292 
=> Migrated TC test_rmvrf_files

common/ops/gluster_ops/mount_ops.py, docs/BP/Ops/mount_ops.md, tests/example/sample_component/test_snap_ops.py
Desciption: Added the method view_snap_from_mount. With this in place, we can check whether the .snaps under the mount dir contains the said list of snaps or not.
Fixes: #875
=> [Common] Adding view_snap_from_mount method

tests/functional/arbiter/test_self_heal_algorithm_full_daemon_off.py, tests/functional/arbiter/test_self_heal_symbolic_links.py
Migrated TC [test_self_heal_symbolic_links](https://github.com/gluster/glusto-tests/blob/master/tests/functional/arbiter/test_self_heal_symbolic_links.py)
And, also updated the TC `test_self_heal_algorithm_full_daemon_off`.
Updates: #292 
=> Migrated TC test_self_heal_symbolic_links

core/result_handler.py
When a single test run is performed for a test
case which is in exclude list, the result handler
throws an exception when the statDict comes out
to be empty.
Added a check specifically for exclude cases.
Fixes: #879
=> [Core] Handling standalone exclude output

common/ops/support_ops/machine_ops.py, tests/functional/glusterd/test_reserved_port_range_for_gluster.py
**Fix:**
- Updated the usage of `remove()` function in list traversal
- Added code too remove the contents of `glusterfind/.keys` in hard_terminate
- Updated the TC to not use `hard_terminate`.
Updates: #890 
=> Updated the usage of remove() in ops

core/parsing/params_handler.py, core/redant_main.py
Added check if the exclude test paths are valid.
If there is even a single invalid path, it is a cause
of worry and hence the framework will spit that out
as an error.
Updates: #698
=> [Core] Exclude test path check

tests/functional/afr/heal/test_afr_self_heal_add_brick_rebalance.py
1. Create a replicated/distributed-replicate volume and mount it
2. Start IO from the clients
3. Bring down a brick from the subvol and validate it is offline
4. Bring back the brick online and wait for heal to complete
5. Once the heal is completed, expand the volume.
6. Trigger rebalance and wait for rebalance to complete
7. Validate IO, no errors during the steps performed from step 2
8. Check arequal of the subvol and all the brick in the same subvol
should have same checksum
Note: This tests is cleary for replicated volume types.
Change-Id: I2286e75cbee4f22a0ed14d6c320a4496dc3c3905
Signed-off-by: Bala Konda Reddy M <bala12352@gmail.com>
* Migrated TC test_afr_self_heal_add_brick_rebalance.py
Updates: #292
=> Migrated TC test_afr_self_heal_add_brick_rebalance.py

common/ops/gluster_ops/snapshot_ops.py, tests/example/sample_component/test_snap_ops.py
Snapshot cloning creates a volume from the snapshot. Now from redant perspective,
the volume data needs to be tracked by environ, which is exactly the purpose of this
patch, to add the volume data to environ if clone succeeds.
Fixes: #887
=> [Common] Snap clone environ changes

core/redant_main.py
The logger_obj has to be the 3rd argument instead of 4th argument.
Fixes: #938
=> [Core] Fixing argument order

common/rexe.py
When a remote command is executed with the help of
ssh, the command is treated as a process at the
remote machine. Hence host system will wait at the
ssh command till the process ends at the remote machine.
If for some reason, the process doesn't end or if
the ssh still thinks that the process hasn't ended,
the flow will be hung at the ssh command.
Fixes: #940
=> [Common] Preventing ssh hang in command execution

tests/functional/afr/heal/test_heal_for_conservative_merge_with_two_bricks_blame.py
Migrated TC [test_heal_for_conservative_merge_with_two_bricks_blame.py](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/heal/test_heal_for_conservative_merge_with_two_bricks_blame.py)
Updates: #292
=> Migrated TC test_heal_for_conservative_merge_with_two_bricks_blame.py

common/ops/gluster_ops/peer_ops.py, tests/functional/afr/test_glustershd_on_newly_probed_server.py, tests/functional/glusterd/test_peer_probe.py
Migrated TC [test_glustershd_on_newly_probed_server](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_glustershd_on_newly_probed_server.py)
And, fixed the TC `test_peer_probe.py`, and updated the `peer_probe_serves`, `peer_detach_servers` op.
Updates: #292 
=> Migrated TC test_glustershd_on_newly_probed_server

common/ops/gluster_ops/brick_ops.py, core/runner_thread.py, tests/functional/snapshot/test_uss_brick_down.py, tools/linting.sh
Migrating the test [test_uss_brick_down.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_uss_brick_down.py)
Also fixing the test_stat handling in runner_thread and making the lint tool a little more descriptive in output.
Updates: #292 
=> [testMigration] Migrating test_uss_brick_down.py

tests/functional/afr/test_git_clone.py
Migrated TC [test_git_clone](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_git_clone.py)
Updates: #292
=> Migrated TC test_git_clone

common/ops/gluster_ops/volume_ops.py
stripCount is not used for any vol types and its
deprecated from gluster too
Removing it will also remove unnecessary logs errors
[2021-08-20 09:45:13,065] ERROR  - Unable to find key stripeCount
in the volume info for the volume test_no_glustershd_with_distribute-dist
=> Remove stripCount variable from volume options

common/ops/gluster_ops/brick_ops.py, common/ops/support_ops/io_ops.py, tests/functional/afr/test_client_io_threads_on_replicated_volumes.py
Migrated TC [test_client_io_threads_on_replicated_volume](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_client_io_threads_on_replicated_volumes.py)
Updates: #292
=> Migrated TC test_client_io_threads_on_replicated_volume

common/ops/support_ops/machine_ops.py, core/environ.py, core/redant_main.py
Added a flag to allow clearing of old glusterfs logs at the time of environment setup. By default, the value is set to True.
Fixes: #980 
=> Added flag for clearing gluster logs

common/ops/support_ops/io_ops.py, tests/functional/afr/test_dir_gfid_heal_on_all_subvols.py
Migrated
[test_dir_gfid_heal_on_all_subvols.py](https://github.com/gluster/glusto-tests/blob/HEAD/tests/functional/afr/test_dir_gfid_heal_on_all_subvols.py)
Updates: #292
=> Migrated test_dir_gfid_heal_on_all_subvols.py

README.md, common/ops/gluster_ops/dht_ops.py, common/ops/support_ops/io_ops.py, core/environ.py, core/redant_main.py, docs/catch_all_exception.md, tests/functional/afr/test_afr_with_snapshot.py, tests/functional/afr/test_afr_with_snapshot_delete.py, tests/functional/afr/test_afr_with_snapshot_rename.py, tests/functional/afr/test_arb_to_repl_conversion_with_io.py, tests/functional/afr/test_client_side_quorum_fixed_with_cross2.py, tests/functional/afr/test_client_side_quorum_with_auto_option.py, tests/functional/afr/test_client_side_quorum_with_auto_option_overwrite_fixed.py, tests/functional/afr/test_client_side_quorum_with_cross2.py, tests/functional/afr/test_client_side_quorum_with_fixed_for_cross3.py, tests/functional/afr/test_client_side_quorum_with_multiple_volumes.py, tests/functional/afr/test_metadata_self_heal_client_side_heal.py, tests/functional/afr/test_multiple_clients_dd_on_same_file_default.py, tests/functional/afr/test_replace_brick_self_heal_io_in_progress.py, tests/functional/afr/test_volume_set_options.py, tests/functional/arbiter/test_data_self_heal_algorithm_diff_default.py, tests/functional/arbiter/test_data_self_heal_algorithm_diff_heal_command.py, tests/functional/arbiter/test_entry_self_heal_heal_command.py, tests/functional/arbiter/test_handling_data_split_brain_of_files_heal_command.py, tools/log_server/log_access.ini, tools/log_server/log_access.py
Changed the default dir for the following,
1. The logs will now be present at `/var/log/redant`
by default.
2. The io scripts will be placed at
`/usr/share/redant/script`.
Fixes: #988 
=> [Core] Changing default dirs

common/ops/support_ops/io_ops.py
This patch fixes the path which was used to
invoke the file_dir_ops.py script.
Updates: #1002
=> [Common] Fixing script invocation path

tests/functional/arbiter/test_metadata_self_heal_on_open_fd.py
Following changes have been done in this patch,
1. Bringing the custom terminate logic completely
under the try-except block as the check flag/variable
might not even be defined before its access.
2. Modified how the self.nodes is formed to
restrict the inclusion of a node more than once in it.
This situation can arise if we were to use the same
node as both server and client.
Note: The test case is failing due to mismatch
in username expected. But this patch is not
a fix for that.
Fixes: #1000
=> [Test] Bringing custom terminate under t-e block

tests/functional/snapshot/test_snap_info_glusterd_restart.py
Migrated TC [test_snap_info_glusterd_restart](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_info_glusterd_restart.py)
Updates: #292 
=> Migrated TC test_snap_info_glusterd_restart

tests/functional/snapshot/test_del_snap.py
Migrated TC [test_del_snap](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_del_snap.py)
Updates: #292 
=> Migrated TC test_del_snap

common/ops/gluster_ops/brick_ops.py
The key in unused_bricks was not removed if the value for that key was 'NONE`. Added a check for that, and also updated the list name to use for servers at the later part of the function.
Fixes: #1002 
=> [Common]Fix form_brick_cmd function

tests/functional/snapshot/test_create_brick_down.py
Migrated TC [test_create_brick_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_create_brick_down.py)
Updates: #292 
=> Migrated TC test_create_brick_down

common/ops/gluster_ops/dht_ops.py, tests/functional/afr/test_repl_heal_with_io.py
Migrated TC [test_repl_heal_with_io](https://github.com/gluster/glusto-tests/blob/master/tests/functional/afr/test_repl_heal_with_io.py)
Added the dht op `find_hashed_subvol`.
Updates: #292 
=> Migrated TC test_repl_heal_with_io

common/ops/gluster_ops/volume_ops.py, tests/functional/snapshot/test_snap_delete_original_volume.py
Migrated TC [test_snap_delete_original_volume](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_delete_original_volume.py)
Also, added a `cleanup_volume` function which handles snap  deletion, stopping and deletion of the volume. As the current `cleanup_volumes` has become more convoluted to handle a complete clearing of volumes.
**NOTE:**
I will send out a different PR to change the name of the current `cleanup_volumes` function to `clear_volumes` and use it only in parent_tests.
Updates: #292
=> Migrated TC test_snap_delete_original_volume

common/ops/gluster_ops/snapshot_ops.py, tests/functional/snapshot/test_snap_status_glusterd_restart.py
Migrated TC [test_snap_status_glusterd_restart](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_status_glusterd_restart.py)
Updates: #292 
=> Migrated TC test_snap_status_glusterd_restart

tests/functional/snapshot/test_restore_online_vol.py
[Migrate TC tests/functional/snapshot/test_restore_online_vol.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_restore_online_vol.py)
Updates: #292 
=> Migrate TC tests/functional/snapshot/test_restore_online_vol.py

common/mixin.py, common/ops/gluster_ops/shared_storage_ops.py, common/ops/gluster_ops/snap_scheduler_ops.py, tests/example/sample_component/test_snap_scheduler_ops.py, tests/functional/glusterd/test_shared_storage.py, tests/functional/snapshot/test_snap_scheduler_status.py
Migrated TC [test_snap_scheduler_status](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_snap_scheduler_status.py)
Updates: #292 
=> Migrated TC test_snap_scheduler_status

tests/functional/snapshot/test_validate_snap_scheduler.py
Migrated TC [test_validate_snap_scheduler](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_validate_snap_scheduler.py)
Updates: #292 
=> Migrated TC test_validate_snap_scheduler

tests/functional/disperse/test_ec_basic.py
[Migrate TC tests/functional/disperse/test_ec_basic.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_basic.py)
Updates: #292
=> Migrate TC tests/functional/disperse/test_ec_basic.py

tests/functional/disperse/test_disperse_eager_lock.py
[Migrate TC tests/functional/disperse/test_disperse_eager_lock.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_disperse_eager_lock.py)
Updates: #292
=> Migrate TC tests/functional/disperse/test_disperse_eager_lock.py

config/config.yml, tests/functional/arbiter/test_data_self_heal_algorithm_diff_heal_command.py, tests/functional/arbiter/test_entry_self_heal_heal_command.py, tests/functional/glusterfind/test_glusterfind_when_node_down.py
Fixed `f-string` issue for a few TCs.
Updated the object name to be `redant` in one TC
Marked a TC as excluded as it works only in downstream RHGS code
=> Fix f-string and object name

common/ops/gluster_ops/volume_ops.py, core/environ.py, tests/d_parent_test.py, tests/functional/glusterd/test_brickmux_brick_process.py, tests/functional/glusterd/test_change_reserve_limit.py, tests/functional/glusterd/test_concurrent_set.py, tests/functional/glusterd/test_create_vol_with_used_bricks.py, tests/functional/glusterd/test_gluster_volume_status_xml_dump.py, tests/functional/glusterd/test_glusterd_quorum.py, tests/functional/glusterd/test_probe_hostname.py, tests/functional/glusterd/test_profile_operations.py, tests/functional/glusterd/test_quorum_syslog.py, tests/functional/glusterd/test_volume_status_xml.py
Updated the usage of the `cleanup_volumes` function within the TCs
Added a peer connection check after forming the cluster, because in the `create_cluster` function
we don't validate the `peer_status ` of the cluster, and as a reason many times the TC fails with the `Peer is not connected` error.
Fixes: #1012 
=> [Common] Updated use of cleanup_volumes function

common/ops/gluster_ops/brick_ops.py, common/ops/gluster_ops/volume_ops.py
Fixed the quorum_type` value check in the brick_ops. The `quorum_type` will be `none` in case
the replica count is 2 and `none` type is not iterable. Hence, added a sanity check for the `quorum_type`
variable before using it.
=> [Common]: Fix quorum_type check

common/ops/gluster_ops/brick_ops.py, tests/functional/disperse/test_nonfop_ecversion.py
Migrated TC [test_nonfop_ecversion](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_nonfop_ecversion.py)
Updates: #292 
=> Migrated TC test_nonfop_ecversion

core/environ.py, tests/functional/disperse/test_ec_check_lock_granted_to_2_different_client.py, tools/file_lock.py
[Migrated TC test_ec_check_lock_granted_to_2_different_client.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_check_lock_granted_to_2_different_client.py)
Updates: #292
=> Migrated TC test_ec_check_lock_granted_to_2_different_client.py

core/environ.py, tests/d_parent_test.py
Missed `redant` object while calling ops from parent_test and environ.
=> Fix: Updated object name

tests/functional/afr/heal/test_data_split_brain_resolution.py, tests/functional/afr/heal/test_metadata_split_brain_resolution.py, tests/functional/afr/test_afr_cli_gfid_splitbrain.py, tests/functional/afr/test_afr_cli_no_splitbrain_resolution.py, tests/functional/afr/test_afr_dir_entry_creation_with_subvol_down.py, tests/functional/afr/test_client_io_threads_on_replicated_volumes.py, tests/functional/afr/test_client_side_quorum_fixed_with_cross2.py, tests/functional/afr/test_client_side_quorum_with_cross2.py, tests/functional/afr/test_client_side_quorum_with_multiple_volumes.py, tests/functional/afr/test_conservative_merge_of_files_heal_command.py, tests/functional/afr/test_dist_to_repl_automatic_heal_should_be_triggered.py, tests/functional/afr/test_manual_heal_full_should_trigger_heal.py, tests/functional/afr/test_manual_heal_should_trigger_heal.py, tests/functional/afr/test_repl_heal_with_io.py, tests/functional/glusterd/test_add_brick.py, tests/functional/glusterd/test_add_identical_brick_new_node.py, tests/functional/glusterd/test_create_vol_with_used_bricks.py, tests/functional/glusterd/test_peer_probe.py, tests/functional/glusterd/test_peer_status.py, tests/functional/glusterd/test_rebalance_hang.py, tests/functional/glusterd/test_replace_brick_quorum_not_met.py, tests/functional/glusterd/test_volume_create.py, tests/functional/glusterd/test_volume_status_xml.py
In python, when we copy a dictionary it creates a new reference to the old dictionary, and thereby if we update the values in
the new (reference) dictionary, then the old one is also affected. The same has been the case in Redant for the `volume_config` that is being used while creating volumes.
The value of the `self.vol_type_inf` dictionary was copied using the `=` operator and then the contents of the new reference/copy were updated as a result the actual dict was also getting updated and caused spurious failures in the CI to run.
**Fix:**
To overcome, this issue it is recommended to use the  `deepcopy()` method in python to copy such dicts, lists so that instead of a new reference, a completely new object is created from the original reference.
Signed-off-by: nik-redhat …
=> Use deepcopy() method for copying dict

tests/functional/disperse/test_ec_basic.py, tests/functional/disperse/test_ec_read_from_hardlink.py, tests/functional/disperse/test_ec_verify_full_heal.py, tests/functional/disperse/test_nonfop_ecversion.py
Migrated TC [test_ec_read_from_hardlink](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_read_from_hardlink.py)
Also, made few other TCs as nonDisruptive.
Updates: #292
=> Migrated TC test_ec_read_from_hardlink

tests/functional/disperse/test_ec_version_healing_when_one_brick_down.py
Migrated TC [test_ec_version_healing_when_one_brick_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_version_healing_when_one_brick_down.py)
Updates: #292
=> Migrated TC test_ec_version_healing_when_one_brick_down

core/test_list_builder.py
If a path for a single TC was provided which didn't start off with `test` then the framework is erroring out as:
`Test Case in exclude list`, which is wrong.  Rather it should error out as `FileNotFoundError`.
**Fix:**
The `os.walk` ignores `listdir()` errors by default and hence if we get a nonexistent path, it doesn't throw any error or exception.
But, it provided an arg `onerror` to check for such exceptions and abort traversal in case of the wrong path.
=> [Core] Fix handling of wrong path for a TC

tests/functional/snapshot/test_uss_snap_active_deactive.py
Migrated TC [test_uss_snap_activate_deactivate](https://github.com/gluster/glusto-tests/blob/master/tests/functional/snapshot/test_uss_snap_active_deactive.py)
Updates: #292 
=> Migrated TC test_uss_snap_activate_deactivate

tests/functional/disperse/test_ec_truncate_file_with_brick_down.py
Migrated TC [test_ec_truncate_file_with_brick_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_truncate_file_with_brick_down.py)
Updates: #292
=> Migrated TC test_ec_truncate_file_with_brick_down

tests/functional/disperse/test_ec_io_hang_clientside_heal.py
[Migrated TC test_ec_io_hang_clientside_heal.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_io_hang_clientside_heal.py)
Updates: #292
=> Migrated TC test_ec_io_hang_clientside_heal.py

tests/functional/disperse/test_ec_io_hang_serverside_heal.py
[Migrated TC test_ec_io_hang_serverside_heal.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_io_hang_serverside_heal.py)
Updates: #292
=> Migrated TC test_ec_io_hang_serverside_heal.py

tests/functional/disperse/test_ec_eager_lock_functional_validation.py
[Migrated TC test_ec_eager_lock_functional_validation.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_eager_lock_functional_validation.py)
Updates: #292
=> Migrated TC test_ec_eager_lock_functional_validation.py

common/ops/gluster_ops/heal_ops.py, tests/functional/disperse/test_ec_io_continuity.py
Migrated TC [test_ec_io_continuity](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_io_continuity.py)
Updates: #292 
igned-off-by: nik-redhat <nladha@redhat.com>
=> Migrated TC test_ec_io_continuity

common/ops/support_ops/io_ops.py, config/config.yml, tests/functional/disperse/test_ec_brick_consumable_size.py, tests/functional/disperse/test_ec_fops.py
[Migrate TC test_ec_brick_consumable_size.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_brick_consumable_size.py)
Updates: #292
=> Migrate TC test_ec_brick_consumable_size.py

common/ops/support_ops/io_ops.py, tests/functional/dht/test_add_brick_rebalance_with_symlink_pointing_out_of_gluster.py
Migrated TC [test_add_brick_rebalance_with_symlink_pointing_out](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_add_brick_rebalance_with_symlink_pointing_out_of_gluster.py)
Added the function `get_md5sum`
Updates: #292 
=> Migrated TC test_add_brick_rebalance_with_symlink_pointing_out

common/ops/support_ops/io_ops.py, tests/functional/dht/test_access_file_with_stale_linkto_xattr.py
Migrated TC [test_access_file_with_stale_linkto_xattr](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_access_file_with_stale_linkto_xattr.py)
Added the function `set_passwd` and `is_linkto_file`
Updates :#292
=> Migrated TC test_access_file_with_stale_linkto_xattr

config/config.yml, tests/functional/disperse/test_ec_file_rename_on_brick_down.py
Migrate TC [test_ec_file_rename_on_brick_down.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/disperse/test_ec_file_rename_on_brick_down.py)
Updates: #292
=> Migrate TC test_ec_file_rename_on_brick_down.py

tests/functional/dht/test_verify_permissions_on_root_dir_when_brick_down.py
Migrate TC [test_verify_permissions_on_root_dir_when_brick_down.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_verify_permissions_on_root_dir_when_brick_down.py)
Updates: #292
=> Migrate TC test_verify_permissions_on_root_dir_when_brick_down.py

common/ops/support_ops/io_ops.py, tests/functional/dht/test_add_brick_rebalance_with_rsync_in_progress.py
Migrated TC [test_add_brick_rebalance_with_rsync_in_progress](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_add_brick_rebalance_with_rsync_in_progress.py)
Updates: #292 
=> Migrated TC test_add_brick_rebalance_with_rsync_in_progress

tests/functional/dht/test_copy_file_subvol_down.py
Migrated TC [test_copy_file_subvol_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_copy_file_subvol_down.py)
Updates: #292
=> Migrated TC test_copy_file_subvol_down

tests/functional/dht/test_copy_dir_subvol_down.py
Migrated TC [test_copy_dir_subvol_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_copy_dir_subvol_down.py)
Updates: #292
=> Migrated TC test_copy_dir_subvol_down

tests/functional/dht/test_remove_brick_with_open_fd.py
Migrate TC [test_remove_brick_with_open_fd.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_remove_brick_with_open_fd.py)
Updates: #292
=> Migrate TC test_remove_brick_with_open_fd.py

tests/functional/dht/test_verify_rebalance_with_locks_on_files.py
Migrate TC [test_verify_rebalance_with_locks_on_files.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_verify_rebalance_with_locks_on_files.py)
Updates: #292
=> Migrate TC test_verify_rebalance_with_locks_on_files.py

tests/functional/dht/test_rename_with_brick_min_free_limit_crossed.py
[Migrated TC test_rename_with_brick_min_free_limit_crossed.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rename_with_brick_min_free_limit_crossed.py)
Updates: #292
=> Migrated TC test_rename_with_brick_min_free_limit_crossed.py

tests/functional/dht/test_healing_of_custom_xattrs_on_newly_added_bricks.py
Migrated TC [test_healing_of_custom_xattrs_on_newly_added_bricks](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_healing_of_custom_xattrs_on_newly_added_bricks.py)
Updates: #292
=> Migrated TC test_healing_of_custom_xattrs_on_newly_added_bricks

tests/functional/dht/test_mkdir_hashdown.py
Migrated TC [test_mkdir_hashdown](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_mkdir_hashdown.py)
Updates: #292 
=> Migrated TC test_mkdir_hashdown

tests/functional/dht/test_rebalance_add_brick_and_lookup.py
Migrated TC [test_rebalance_add_brick_and_lookup](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_add_brick_and_lookup.py)
Updates: #292 
=> Migrated TC test_rebalance_add_brick_and_lookup

tests/functional/dht/test_rebalance_peer_probe.py
Migrated TC [test_rebalance_peer_probe](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_peer_probe.py)
Updates: #292 
=> Migrated TC test_rebalance_peer_probe

tests/functional/dht/test_rebalance_preserve_user_permissions.py
Migrated TC [test_rebalance_preserve_user_permissions](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_preserve_user_permissions.py)
Updates: #292 
=> Migrated TC test_rebalance_preserve_user_permissions

common/ops/gluster_ops/dht_ops.py, common/ops/gluster_ops/volume_ops.py
Issue:
Sometimes, on using the hostnames fetched from xattr returns FQDNs/hostname instead of the IP of the node.
But, redant is configured to work only with IP addresses as a result the TCs failed in such scenarios.
Fix:
Added code to convert hostnames to IP in such functions which take the return values of xattrs and then execute the remote-executioner.
=> [Common] Update hostnames to IP in DHT Ops

common/ops/gluster_ops/mount_ops.py, common/ops/support_ops/io_ops.py, tests/functional/dht/test_rebalance_with_acl_set_to_files.py
Migrate TC [test_rebalance_with_acl_set_to_files.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rebalance_with_acl_set_to_files.py)
Updates: #292
=> Migrate TC test_rebalance_with_acl_set_to_files.py

tests/functional/dht/test_rename_dir_subvol_down.py
Migrated TC [test_rename_dir_subvol_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rename_dir_subvol_down.py)
Updates: #292 
=> Migrated TC test_rename_dir_subvol_down

tests/functional/dht/test_directory_custom_extended_attributes.py
Migrated TC [test_directory_custom_extended_attributes](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_directory_custom_extended_attributes.py)
Updates: #292 
=> Migrated TC test_directory_custom_extended_attributes

tests/functional/dht/test_rmdir_subvol_down.py
Migrated TC [test_rmdir_subvol_down](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_rmdir_subvol_down.py)
Updates: #292 
=> Migrated TC test_rmdir_subvol_down

common/ops/gluster_ops/volume_ops.py, tests/functional/dht/test_file_rename_when_destination_file_stored_on_source_file_hashed_subvol.py
Migrated TC [test_file_rename_when_destination_file_stored_on_source_file_hashed_subvo](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_file_rename_when_destination_file_stored_on_source_file_hashed_subvol.py)
Updates: #292 
=> Migrated TC test_file_rename_when_destination_file_stored_on_source_file_hashed_subvo

tests/functional/dht/test_dht_file_rename_when_destination_file_exists.py
Migrated TC [test_dht_file_rename_when_destination_file_exists](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_dht_file_rename_when_destination_file_exists.py)
Updates: #292 
=> Migrated TC test_dht_file_rename_when_destination_file_exists

tests/functional/dht/test_dht_file_rename_when_dest_is_hashed_or_cached_to_diff_subvol_combinations.py
Migrated TC [test_dht_file_rename_when_dest_is_hashed_or_cached_to_diff_subvol_combinations](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_dht_file_rename_when_dest_is_hashed_or_cached_to_diff_subvol_combinations.py)
Updates: #292
=> Migrated TC test_dht_file_rename_when_dest_is_hashed_or_cached_to_diff_subvol_combinations

tests/functional/dht/test_file_rename_when_destination_file_doesnot_exist.py
[Migrate TC test_file_rename_when_destination_file_doesnot_exist.py](https://github.com/gluster/glusto-tests/blob/master/tests/functional/dht/test_file_rename_when_destination_file_doesnot_exist.py) 
Updates: #292
=> Migrate TC test_file_rename_when_destination_file_doesnot_exist.py

common/ops/support_ops/machine_ops.py, common/rexe.py, config/config.yml
Updated the `reboo_node` function to use the paramiko `exec_command` function directly, and raise an
exception in case of an issue.
The reason to not use the existing `execute_command` function is, that function tries to reconnect to the node, in case of an exception which we don't want in this case.
Fixes: #940 
=> [Commom] Updated the reboot_node code

common/ops/gluster_ops/heal_ops.py, common/ops/gluster_ops/volume_ops.py, config/config.yml, tests/functional/afr/heal/test_data_split_brain_resolution.py, tests/functional/afr/heal/test_metadata_split_brain_resolution.py, tests/functional/afr/test_afr_cli_gfid_splitbrain.py, tests/functional/afr/test_dir_gfid_heal_on_all_subvols.py, tests/functional/afr/test_gfid_split_brain_resolution.py, tests/functional/afr/test_heal_split_brain_command.py, tests/functional/afr/test_split_brain_with_hard_link_file.py, tests/functional/arbiter/test_no_data_loss_arbiter_vol_after_rename_file.py, tests/functional/arbiter/test_oom_on_client_heal_is_in_progress_arbiter.py, tests/functional/arbiter/test_resolving_meta_data_split_brain_extended_attributes.py, tests/functional/arbiter/test_verify_metadata_and_data_heal.py, tests/functional/glusterd/test_default_max_bricks_per_process.py
Marked the TC `test_shared_storage` as excluded and added sleep in some TCs to compensate
for a remount of volume after a restart of bricks for a volume. 
**NOTE:""
It is not ideal to add a sleep for in these TCs, but it has been done to adjust for all types of env and gluster installation.
=> Added sleep in some TCs to compensate for mounting of volume after a restart

common/ops/gluster_ops/volume_ops.py
The brick_path which was checked against the bricks from the volume_info consists of the file/folder names as well.
As a result the type check always used to fail out. 
Hence, modified the check to check for bricks from volume info in the given path. (Vice versa of the current check)
=> Fix: get_volume_type_from_brick function

config/config.yml, tests/flaky/afr/test_gfid_heal.py, tests/flaky/afr/test_heal_fail_1x3.py, tests/flaky/arbiter/test_handling_data_split_brain_of_files_heal_command.py, tests/flaky/dht/test_one_brick_full_add_brick_rebalance.py, tests/flaky/disperse/test_ec_truncate_file_with_brick_down.py, tests/flaky/disperse/test_ec_verify_full_heal.py, tests/flaky/fuse_subdir/test_node_reboot_subdir_mounted.py, tests/flaky/glusterd/test_bricks_online_after_node_reboot.py, tests/flaky/glusterd/test_reserved_port_range_for_gluster.py, tests/flaky/glusterd/test_verify_df_output.py, tests/flaky/glusterfind/test_gfind_delete_file.py, tests/flaky/glusterfind/test_gfind_modify_files.py, tests/flaky/glusterfind/test_gfind_rename.py, tests/functional/afr/heal/test_server_side_healing_happens_only_when_glustershd_running.py, tests/functional/glusterfind/test_gfind_modify_files.py, tests/functional/glusterfind/test_gfind_rename.py
Occasionally, a few tests fail when run along with the other tests (or as a complete module) due to some race conditions in gluster, but works fine when run individually they pass.
Added a new category `flaky`, which consists of these occasional failing tests.
=> Marking spurious tests as flaky

README.md, common/ops/support_ops/machine_ops.py, config/config.yml, core/redant_main.py, tests/functional/afr/heal/test_server_side_healing_happens_only_when_glustershd_running.py, tests/functional/dht/test_file_creation.py
Updated the README to have the pre-requisites for running redant TCs.
Updated the heal timeout in a TC.
Fixed hostname to IP conversion in a TC and removed the `iptable --flush` command as that issue
was resolved in glusterfs itself.
=> Doc: Update setup instructions

core/test_list_builder.py, tests/functional/dht/test_verify_permissions_on_root_dir_when_brick_down.py
The condition to check for config was incorrect, it filtered out the "Genric" volumes as well.
Updated the code to use "OR" instead of "AND" for the check.
Also, updated a DHT tc to `disruptive` type as it restarted glusterd in the test.
=> Core: Fix vol type check in test list builder

common/ops/support_ops/machine_ops.py, tests/functional/arbiter/test_resolving_meta_data_split_brain_extended_attributes.py, tests/functional/arbiter/test_self_heal_symbolic_links.py, tests/functional/arbiter/test_split_brain.py, tests/functional/disperse/test_ec_io_hang_clientside_heal.py, tests/functional/glusterd/test_validate_glusterd_info.py
This PR covers glusterd, disperse, arbiter modules for upstream TCs.
After this, only AFR and DHT would be left.
=> Marked arbiter, glusterd,disperse modules for upstream TCs
